### PR TITLE
Added test for Noise ID (tentative toe in the water)

### PR DESCRIPTION
**Pull request by kevinpowe**
Hi! This is a very tentative toe in the water to start adding test coverage to wrap my head around the codebase. I've added a test for Noise that appears to do the right thing locally.

### CODE REVIEW

**Comment by JoelCFC25** [comment]
It's not a *huge* thing, but it could also be extended to show that Noise will still mill the Corp during the Corp's turn (e.g., installing a virus with a Clone Chip).

**Comment by kevinpowe** [comment]
@JoelCFC25 Great suggestion! I'll put that on my to-do list once I've skilled up a little more. ;-)

**Comment by nealterrell** [comment]
Welcome aboard 👍

**Comment by kevinpowe** [comment]
Understood re: alphabetizing, @Saintis. I'll look at the suggested enhancements and add that to the list for a second pass.

Thank you for the feedback all - makes ramping up much easier!

**Pull request merged**
