### PR TITLE
fix Frame Job, Monolith tweak, add Helium-3 Deposit

### LINKED ISSUE #277: Frame Job is unplayable
Frame Job cannot be played from hand at all (no clicks or credits deducted, card is immobile and doesn't respond at all). I manually boosted my clicks and credits prior to testing it to be sure I met all the requirements. 

The current code is: 

`{:additional-cost [:forfeit] :effect (effect (gain :corp :bad-publicity 1))}`

I'm not sure if this is where it's bogging down, but the forfeit is not actually an additional cost, it's the outcome of the event. If `:additional-cost` got dropped and `:forfeit` was moved into the `:effect`, would that make it work? Basically it would be altered to look more like Data Dealer.

### PR DESCRIPTION
**Pull request by JoelCFC25**
Fixes #277. Removes the forfeit from the cost and makes it the effect instead. Tested and verified working.

### CODE REVIEW

**Comment by JoelCFC25** [comment]
Implemented Helium-3 Deposit. Since the system doesn't (yet) distinguish between agenda counters, virus counters, or power counters, technically this can be used incorrectly, so it does require players to choose a valid target. Tested and verified that it adds power counters to Corp or Runner cards (Atman being the test case as the only Runner card you'd likely ever target).

**Comment by JoelCFC25** [comment]
I'm on a roll tonight--with the insight granted by @nealterrell about the differences between `:req` and `:effect` I finally pulled together Monolith's discounted program installs after getting stuck for several days.

**Comment by DominicKexel** [comment]
@JoelCFC25 So, what is the difference between `:req` and `:effect`? :-)

**Comment by nealterrell** [comment]
These look good, Joel. Nice job :).

**Comment by mtgred** [comment]
:+1:

**Pull request merged**
