### PR TITLE
Add Docker files to support personal deployments

### LINKED ISSUE #7516: setting up a production instance
I am looking into setting up a production for my own testing. I have a couple of questions regarding the approach used by jinteki.net. 

What I have done so far is to build the uberjar with a prod.edn defined in the resources folder which gets embedded into the jar. I am planning to set up a webserver to serve the static files, those below resources/public.

Is it approximately what is done on jinteki.net? 

Also, do you bundle the prod.edn file into the jar? I would think that is better to have it outside to allow managing the configuration independently. 

Finally, I have a visual warning that shadow-cljs is not able to connect. I am surprised by this as I would assume that the server/mode prod would disable shadow-cljs entirely.

Thanks in advance for the help.

I will be happy to write to documentation once my setup is working.

p.s.: I will accept a RTFM :-)

### PR DESCRIPTION
**Pull request by xdg**
This commit adds Dockerfiles to create images to support production deployment of personal jnet servers using Docker Compose.

There are three new Dockerfiles for three images:

* Dockerfile.cards -- bundles card images with nginx for serving as static files under /img/cards.
* Dockerfile.initdb -- bundles mongorestore and a dump of the initial database for use populating database independent of the repo.
* Dockerfile.prod -- builds and bundles an uberjar of the application along with the generated public resources.

An example docker-compose.yml file for using these images may be found at https://gist.github.com/xdg/048d0a15580d71948f4c2c1c02353ae0

Closes #7516

### CODE REVIEW

**Comment by xdg** [comment]
I've drafted a guide for how to use the Docker images these files will create: [Setting up a personal jinteki.net clone](https://docs.google.com/document/d/1OwbsgOw2MtkUYvPmv1ywamwt7a3J63x4LY1doOcnwB0/edit?usp=sharing).

**Comment by NBKelly** [comment]
Does this close #7516?

**Comment by xdg** [comment]
Well, as Larry Wall used to say "TIMTOWTDI".  So people might want to deploy to production more like jinteki.net rather than my approach. But this PR and the instructions I wrote should help people achieve the end result of what is desired from #7516.

I think I need to update this PR to either bundle a prod.edn or work out how to load it externally with docker compose and document that. I like the externally configured approach so that end users can modify their jnet config without needing to rebuild the image.

**Comment by xdg** [comment]
I rebased this to v135 (so I can build a new image from there) and modified the docker exec to allow setting an external prod.edn file.  I'll update my google docs with instructions.

I think this is now good to go and will address the needs of 7516.

I have deployed 3 private jnets this week.  The first followed my instructions from scratch (fixing docs bugs as I went!) so I'm pretty confident this is functional as useful to people.  The other two added new sections to an existing docker-compose.yml file after following instructions for initializing a database for each one.

**Comment by acollign** [comment]
> Well, as Larry Wall used to say "TIMTOWTDI". So people might want to deploy to production more like jinteki.net rather than my approach.

Right, the PR #7529, which fixes #7516 as well, is taking a similar yet distinct approach to building and running the stack. The choice is yours regarding which contribution you prefer :-). If that makes sense, we could also pick and choose the best part of both approaches. Happy to contribute.

**Comment by xdg** [comment]
Rebased to v136.1

**Comment by NoahTheDuke** [comment]
status?

**Comment by xdg** [comment]
@acollign can we merge this as is?  As I said in [this comment](https://github.com/mtgred/netrunner/pull/7529#issuecomment-2392724004), I think this PR can be  used as a base for your work. I don't think my approach  here  precludes anything you're trying to do there.

**Comment by xdg** [comment]
Rebased to v137

**Comment by acollign** [comment]
> @acollign can we merge this as is? As I said in [this comment](https://github.com/mtgred/netrunner/pull/7529#issuecomment-2392724004), I think this PR can be used as a base for your work. I don't think my approach here precludes anything you're trying to do there.

Sure! Please go ahead. Sorry to the delay, I am not able to focus on netrunner these days.

**Pull request merged**
