### PR TITLE
some fixes

### LINKED ISSUE #2591: NEXT Wave 2 can be re-resolved by Bifrost and 24/7
https://netrunnerdb.com/en/card/12009

According to the UFAQ ruling on the card, Bifrost Array and 24/7 News Cycle cannot resolve NEXT Wave 2 because there isn't an explicit "when scored" ability on it. However, jinteki.net currently allows you to resolve the brain damage in both of those situations.

### LINKED ISSUE #2600: Message when runner accesses a server with no cards in it
It would be nice if, when the runner successfully runs a server with no cards in it (IE: empty HQ with nothing in the root), there was a message akin to:

"There are no cards to access in [server]."

### LINKED ISSUE #2640: Architect install number is open information.
When you install a card from R&D via Architect, which card it was (e.g. the 2nd from the top) is supposed to be open information. It would be great if the log messages declare which number card was chosen.

### LINKED ISSUE #2644: Accountsiphon interaction with Counter surveilence
vincentkbl spends  and 1  to install Counter Surveillance.
vincentkbl spends  to play Account Siphon.
vincentkbl uses Ken "Express" Tenma: Disappeared Clone to gain 1 .
vincentkbl spends 1  to use Eater to break ICE subroutine and access 0 cards this run.
amm has no further action.
amm uses Kakugo to do 1 net damage.
vincentkbl trashes Dirty Laundry due to damage.
vincentkbl continues the run.
vincentkbl sets credit to 15 (-1).
vincentkbl sets credit to 14 (-1).
amm has no further action.
vincentkbl continues the run.
amm has no further action.
vincentkbl uses Account Siphon to access cards by paying 8 .
vincentkbl accesses Biotic Labor from HQ.
vincentkbl accesses Fetal AI from HQ.
amm uses Fetal AI to do 2 net damage.
vincentkbl trashes Special Order, Logos due to damage.
vincentkbl pays 2 to steal Fetal AI.
vincentkbl steals Fetal AI and gains 2 agenda points.
vincentkbl accesses Hokusai Grid from HQ.
vincentkbl accesses Ben Musashi from HQ.

### LINKED ISSUE #2645: Wasteland shouldn't trigger when you trash corp cards
[Wasteland](https://netrunnerdb.com/en/card/09036) gives 1 credit when you trash one the corp's installed cards. It should only give credits when the runner trashes his own cards.

### LINKED ISSUE #2657: Runner has to use /close-prompt after Meteor Mining is scored
Apparently after it is scored, 7 credits were taken.  All seemed well, except runner side it said still waiting for corp to resolve.

### PR DESCRIPTION
**Pull request by danhut**
fix #2645 
fix #2644 
closes #2640 
closes #2600 
fix #2591 
fix #2657

### CODE REVIEW

**Comment by danhut** [comment]
Doh... will sort it out.  Should the position in Archives part be kept?  I think that should be known too?

**Comment by danhut** [comment]
All sorted.  Good to merge.

**Comment by LiteSpecter** [comment]
The Archives install position from Architect should be removed; the order of facedown cards does not need to be maintained in archives is not open information as implied by the server definition on page 6 of the core rules. Since archives order is naturally maintained on Jinteki, the information of card install # can unfortunately be partially deduced by the runner already. This could be fixed by allowing archives reorder or by forcing facedown cards to the top of Archives, but that seems like a very low priority fix.

**Comment by danhut** [comment]
I have reverted the architect message.  Part of my open pull request so will flow through in a few days/weeks

**Pull request merged**
