### PR TITLE
Utility to make testing some card properties easier

### PR DESCRIPTION
**Pull request by nealterrell**
Big discussion on this in the Slack channel, but in general, cards that use `:choices` to target another card have to account for both keywords and strings as property values because of the way JSON data is handled when sent back to the game server. This utility `card-is?` should make it easier to account for the difference... so rather than write code like `(or (= (:side %) "Corp") (= (:side %) :corp))`, you can write `(card-is? % :side :corp)` and the utility will do the work to determine if it's a string, needs to be converted to a keyword, etc.

Includes @JoelCFC25's test case for Shipment from SanSan, which was the inspiration, and some improvements based on @zaroth's work.

### CODE REVIEW

**Comment by mtgred** [comment]
There is merge conflict. Can you have a look at it?

**Comment by nealterrell** [comment]
Huh, thought I fixed it. One minute.

**Comment by nealterrell** [comment]
Merged.

**Comment by zaroth** [comment]
:+1: Definitely want this!

**Pull request merged**
