### PR TITLE
FIX: Product Recall trash bonus miscalculation

### LINKED ISSUE #3560: Product Recall incorrectly calculating trash cost in IG
When using product recall in Industrial Genomics, it is counting both face down and face up cards in Archive to calculate trash cost.  It should only use face down.

In fact it is worse than that.  Trashing a 3 trash cost card, with 6 face down and 4 faceup in archives gave me 15.

### PR DESCRIPTION
**Pull request by NoahTheDuke**
Product Recall was clearing the trash bonus at the end of the effect instead of at the beginning, which caused lingering trash cost bonuses to be rolled into the new calculations when `:pre-trash` was triggered within the card effect.

This fixes that bug and adds a test to handle the case.

Fixes #3560

### CODE REVIEW

**Comment by Saintis** [comment]
Does this work with encryption protocol?

**Comment by NoahTheDuke** [comment]
Should work fine. It calls `(trigger-event :pre-trash)` to get those updates and then calls `(trash-cost)` to get the most up-to-date trash cost information, given all bonuses.

**Comment by nealterrell** [comment]
I think I'd rather write something equivalent to `modified-install-cost` instead of doing the dissoc and trigger manually in a card definition (which is a bit of a code smell).

**Comment by NoahTheDuke** [comment]
Done!

**Pull request merged**
