### PR TITLE
Namespaced Card Definitions

### PR DESCRIPTION
**Pull request by NoahTheDuke**
I am not a big fan of polluting namespaces, and the way we do things isn't quite idiomatic Clojure. Instead of keeping the entire game in the main namespace, it's better to keep each section in it's own namespace. Sadly, the interwoven nature of the game means it would be a monumental task to do so with the core. Thankfully, it's much easier to do so with the cards, as I've done here.

This gives each card type it's own namespace, loads all of them instead of requiring them in some way, filters on the namespaces, and merges the card definitions in a way that allows for functional hot reloading of the card definitions. (Props to @Odie for creating [this example](https://github.com/Odie/card-example/) which I adapted. Also h/t to Suskeyhose and sarna on clojure discord for their input as well!)

This also includes a fixture that can be added for use with `test-refresh`: `(use-fixtures :once load-all-cards reload-cards)` will now reload the card definitions instead of forcing you to restart test-refresh completely.

~However, this makes compilation 2-3 times as slow, and enabling card-reloading makes individual tests about 2-4 times as slow.~ 

NO LONGER TRUE - UPDATED BELOW

The below were run on Windows 10 Pro, i7 2.6 GHz, 8 GB ram, on Powershell

~Comparison of compile times with the command `lein clean; Measure-Command {lein compile | Out-Default}`:~
* ~Current:~
~Minutes           : 3
Seconds           : 46
Milliseconds      : 19
Ticks             : 2260195103~
* ~Namespaced:~
~Minutes           : 5
Seconds           : 13
Milliseconds      : 499
Ticks             : 3134999057~

~Comparison of test-refresh, no hot reloading:~
* ~Current:~
~Ran 861 tests containing 6185 assertions.
0 failures, 0 errors.~

~Passed all tests
Finished at 17:49:26.615 (run time: 43.289s)~

* ~Namespaced;~
~Ran 861 tests containing 6185 assertions.
0 failures, 0 errors.~

~Passed all tests
Finished at 17:43:19.086 (run time: 87.225s)~

~Comparison of test-refresh auto-running tests:~
* ~Current, after adding a space to a blank line:~
~:reloading (game-test.cards.agendas)~

~Ran 108 tests containing 1183 assertions.
0 failures, 0 errors.~

~Passed all tests
Finished at 17:47:30.481 (run time: 7.777s)~
* ~Namespaced, after adding `(prn "heck")` to 15 Minutes:~
~:reloading (game-test.cards.agendas)
"heck"~

~Ran 108 tests containing 1183 assertions.
0 failures, 0 errors.~

~Passed all tests
Finished at 17:51:46.496 (run time: 26.541s)~

### CODE REVIEW

**Comment by Saintis** [comment]
I do like the new name space thing, but if compile and test times are much longer I'm not sure it's that benefitial...

**Comment by NoahTheDuke** [comment]
With a full PR from @Odie, I've increased the speed dramatically. Maybe my computer's running hot today? Who knows. But now compile times are significantly closer, and test times are near even.

Odie parallelized the loading process, and deferred actually loading the card definitions into `cards` until run-time. Previously, the card definitions were being both compiled _and_ loaded into `cards` at compile time. I changed the loading process to happen every time instead of just when `cards` is `nil`, so they now feature hot-reloading, which means that test-refresh does what we expect: fully retests cards as they're changed. (Sadly, test-refresh only reruns the tests when a test file is changed, so you can't _just_ make a change to a card definition, you have to also re-save the test file to trigger a rerun.)

Comparison of compile times with `lein clean; Measure-Command {lein compile | Out-Default}`:
* Current:
```powershell
Minutes           : 2
Seconds           : 16
Milliseconds      : 205
Ticks             : 1362053069
```
* Name-spaced:
```powershell
Minutes           : 2
Seconds           : 11
Milliseconds      : 301
Ticks             : 1313018283
```

Comparison of test times with `lein clean; lein compile; Measure-Command {lein test | Out-Default}`:
* Current:
```powershell
Minutes           : 0
Seconds           : 43
Milliseconds      : 991
Ticks             : 439913846
```
* Name-spaced:
```powershell
Minutes           : 1
Seconds           : 55
Milliseconds      : 126
Ticks             : 1151267340
```
Comparison of test-refresh times with `lein clean; lein compile; Measure-Command {lein test-refresh | Out-Default}`:
* Current:
```powershell
Ran 861 tests containing 6185 assertions.
0 failures, 0 errors.

Passed all tests
Finished at 11:39:11.737 (run time: 42.450s)
```
* Name-spaced;
```powershell
Ran 861 tests containing 6185 assertions.
0 failures, 0 errors.

Passed all tests
Finished at 10:40:34.756 (run time: 127.728s)
```

Comparison of test-refresh auto-running tests with `lein clean; lein compile; lein test-refresh`:
* Current, after adding a space to a blank line:
```powershell
:reloading (game-test.cards.agendas)

Ran 108 tests containing 1183 assertions.
0 failures, 0 errors.

Passed all tests
Finished at 11:39:44.955 (run time: 4.811s)
```
* Name-spaced, after adding `(prn "heck")` to 15 Minutes:
```powershell
:reloading (game-test.cards.agendas)
"heck"
"heck"

Ran 108 tests containing 1183 assertions.
0 failures, 0 errors.

Passed all tests
Finished at 11:46:38.501 (run time: 10.936s)
```

**Comment by NoahTheDuke** [comment]
Updated to only load the type that's changed. This dramatically improves the speed across the board.

Leaving out the comparisons this time:

`lein clean; Measure-Command {lein compile | Out-Default}`:

```powershell
Minutes           : 2
Seconds           : 8
Milliseconds      : 377
Ticks             : 1283773475
```

`lein clean; lein compile; Measure-Command {lein test | Out-Default}`:
```powershell
Minutes           : 1
Seconds           : 3
Milliseconds      : 69
Ticks             : 630697245
```
`lein clean; lein compile; Measure-Command {lein test-refresh | Out-Default}`:
```powershell
Ran 861 tests containing 6185 assertions.
0 failures, 0 errors.

Passed all tests
Finished at 14:33:24.049 (run time: 57.948s)
```

`lein clean; lein compile; lein test-refresh`:

```powershell
:reloading (game-test.cards.agendas)
"heck"
"heck"

Ran 108 tests containing 1183 assertions.
0 failures, 0 errors.

Passed all tests
Finished at 14:34:21.651 (run time: 4.976s)
```

**Comment by Saintis** [comment]
Neat! Let's switch!

**Pull request merged**
