### PR TITLE
basic support for touch devices

### PR DESCRIPTION
**Pull request by queueseven**
tested on Windows 10 and Android

### CODE REVIEW

**Comment by davide-ceretti** [comment]
You might want to trim whitespaces before committing. Many editors give you the ability to do it automatically after each save.

**Comment by queueseven** [comment]
@davide-ceretti  good catch. I switched to good old Notepad++; have to train myself to use <kbd>ALT</kbd>+<kbd>SHIFT</kbd>+<kbd>S</kbd> instead of <kbd>CTRL</kbd>+<kbd>S</kbd>.

**Comment by sjohnc** [comment]
I pulled this down and cherry-picked these commits on top of the current tip. I then tried it out, it works well for the most part. I seemed to have issues on an Indexing run getting the cards to go into the corp R&D. The cards would just go into the play field face up. I couldn't get them to go back into R&D.

**Comment by JoelCFC25** [comment]
Superseded by #1217.

**Pull request closed without merging**
