### PR TITLE
fix Regenesis not revealing the agenda in Archives

### LINKED ISSUE #6928: Regenesis does not trigger Hyoubu
When scoring Regenesis and triggering it's ability (revealing an agenda), it does not trigger Hyoubu (which givea a credit if it reveal a card).
Thank you.
Diogene

### PR DESCRIPTION
**Pull request by francescopellegrini**
Fixes #6928

### CODE REVIEW

**Comment by NoahTheDuke** [comment]
You have to actually wrap the rest of the function in the wait-for and then pass the eid into a competing function (effect-completed, most likely).

**Comment by NoahTheDuke** [comment]
Ah crap, I forgot to mention/assumed you'd know that if you're doing an awaitable effect, you need `:async true` on the ability map.

**Comment by francescopellegrini** [comment]
> Ah crap, I forgot to mention/assumed you'd know that if you're doing an awaitable effect, you need `:async true` on the ability map.

My bad, it's been a while since my last contribution... 😅

**Comment by NoahTheDuke** [comment]
It's all good, it's been a while since mine too :grimacing:

**Comment by francescopellegrini** [comment]
Is there anything against merging this PR?

**Pull request merged**
