### PR TITLE
Crescentus should only work on rezzed ICE

### LINKED ISSUE #1441: Crescentus targeting unrezzed ice reveals information.
Crescentus can be triggered, and targeted to an unrezzed ice. Doing so will trash Crescentus, leave ice unrezzed, but generate a line in the text log: "Player derezzes Archer". 

So it is possible to learn what ice lies unrezzed by mis-using Crescentus.

### PR DESCRIPTION
**Pull request by queueseven**
fixes #1441

### CODE REVIEW

**Comment by mtgred** [comment]
There is a conflict. Can you have a look?

**Comment by queueseven** [comment]
I fixed the conflict. circleci complains about

> Your build has exceeded the memory limit of 4G on 1 container.

huh?

**Comment by zaroth** [comment]
maybe the amount of tests Joel provided broke the CI's bank? ;-)

**Comment by JoelCFC25** [comment]
That happened to me once last week--just rerun CircleCI and I bet it'll pass.

**Comment by mtgred** [comment]
👍

**Pull request merged**
