### PR TITLE
Forfeit Targeting

### LINKED ISSUE #2801: Archer agenda sacrifice should use card targeting
It currently uses a dialogue box. This is a problem when, for example, the corp has two Project Atlas scored and only one has a token. When Archer is rezzed, the corp obviously wants to sacrifice the PA without the token, but has to guess which agenda is without the token.

### PR DESCRIPTION
**Pull request by Saintis**
Changes forfeit costs to use a target instead text choices.

Updates tests to work with the new system and rewrote Success and Quarantine System to still work.

Refactored the cost function a little bit.

Fixes #2801.

### CODE REVIEW

**Comment by JoelCFC25** [comment]
There are a couple of outstanding Success bugs--is this going to fix those?

**Comment by Saintis** [comment]
Also fixes #2704.

**Comment by mtgred** [comment]
Great!

There are some conflicts with the latest merges. Can you have a look at it?

**Comment by Saintis** [comment]
Merge conflicts resolved. Blocked by my own PR 😉

**Comment by Saintis** [comment]
Hmm, will check what is failing...

**Comment by Saintis** [comment]
Should be fixed now.

**Comment by mtgred** [comment]
👍

**Pull request merged**
