### PR TITLE
Add MIT license

### PR DESCRIPTION
**Pull request by nikolasavic**

### CODE REVIEW

**Comment by zaroth** [comment]
I compared it with the MIT License notice jQuery uses: https://github.com/jquery/jquery/blob/master/LICENSE.txt

I don't think this part relates to us:

     The following license applies to all parts of this software except as
      documented below:

**Comment by JoelCFC25** [comment]
Fixes #402!

**Comment by mtgred** [comment]
👍

**Comment by jhli** [comment]
Cool! I could have lived with gpl too but mit dies the job as well.

**Pull request merged**
