### PR TITLE
Enable rejoining of games after a browser refresh / "leave-game"

### PR DESCRIPTION
**Pull request by nealterrell**
Currently a `reconnect` message is sent when a client's websocket experiences a brief disconnect from the web server. This solution is fragile and doesn't work if the disconnection lasts for more than some unknown time. It also does not work if the user accidentally leaves the game or refreshes the browser.

This PR adds a Rejoin button on the game lobby for any game that you've left by either disconnect, page refresh, or Leave Game button. Rejoining causes the game server to emit a full game state, allowing the client to reinitialize the game board.  A rejoinable game shows up first in the game list.

This could use a once-over by anyone with some time.

### CODE REVIEW

**Comment by danhut** [comment]
This one deserves a big pat on the back. Nice work!

**Comment by mtgred** [comment]
Amazing!

There's a merge conflict with the latest merges. Can you have look at it?

**Comment by nealterrell** [comment]
Fixed.

**Comment by mtgred** [comment]
👍

**Pull request merged**
