### PR TITLE
fix for tag check in Reality Threedee

### PR DESCRIPTION
**Pull request by mharris717**
Before this change, Reality Threedee was giving $2 every time. After this change it is working correctly. 

I am still very new to Clojure, and I only know enough to make sense of the code at a basic level.  You'll need to look at the change and see if it makes sense. I can only speak to the results of my testing. 

Thank you so much for jinteki.net, it's amazing.

### CODE REVIEW

**Comment by mharris717** [comment]
Just saw the failing circleci build. I'll check it out tomorrow if I have time. 

I suspect the fix would take 10 seconds for you, but I'm enjoying learning the codebase.

**Comment by mharris717** [comment]
Do you have any tips for recreating the lein test on circleci on a dev machine? Doing lein test locally gives 0 tests run.

**Comment by mharris717** [comment]
Ah, needed to add tagged to the let in the msg macro. 

Again, I have no idea if this is a start change to make. I won't be offended if you reject it. 

Thanks again for all your hard work.

**Comment by mtgred** [comment]
You commit looks good. :+1:

**Comment by mtgred** [comment]
There is currently no test running. But Circle CI tries to compile the Clojure code. To simulate that, you can just do `lein uberjar`.

**Pull request merged**
