### PR TITLE
Added chameleon/london library tests

### PR DESCRIPTION
**Pull request by kevkcc**
I noticed Utopia Shard could not be installed through a Sneakdoor Beta run without accessing so I added a bit of code to allow this. I'm not 100% sure if this is the way it should be approached but as this is the only card that allows you to do this, I figure an extra check is simple enough to do. Comments are welcome.

Added Chameleon unit tests for my last commit as Joel requested. Also did one for London Library since it had issues with Chameleon in the past. Added one for Utopia Shard as well. Fixed a small typo in London Library print message as well.

### CODE REVIEW

**Comment by zaroth** [comment]
Naming cards like this is usually awkward, but this case seems specific enough. Looks good to me :+1:

**Comment by zaroth** [comment]
... But could get better ;-) Just read this in chat on jinteki.net:

> btw played a game yesterday and seems like nerve agent doesnt work with sneakdoor

Could you maybe try cooking up a more general solution which would also solve this case?

**Comment by JoelCFC25** [comment]
See #955 for that one.

**Comment by kevkcc** [comment]
Thanks for the feedback. I definitely agree that tying specific cards together is not ideal hence why I was unsure about my approach in the first place. Luckily I've since come up with what I believe to be a better solution that doesn't require changes to Utopia Shard at all (involves changing up the run timing on Sneakdoor Beta) so I have reverted that particular change.

Regarding Nerve Agent + Sneakdoor, I've thought about it and can pinpoint exactly where the problem is but cannot come up with a good solution for now. To my knowledge, #955 is not entirely accurate - Nerve agent works with run events like Dirty Laundry and Legwork, it's only because of the switch in the run from Archives to HQ on Sneakdoor that causes problems. But I'll keep thinking about this one.

**Comment by mtgred** [comment]
There are some merge conflicts. Can you have a look?

**Comment by kevkcc** [comment]
Fixed the merge conflicts. Unfortunately I won't have time to investigate Nerve Agent too much for next couple of weeks but for now Utopia and possibly some other weird Sneakdoor edge cases now work.

**Comment by kevkcc** [comment]
Apologies but I thought of a new scenario last night and my code does not work with Crisium Grid. I have reverted the change because I won't have too much time in the coming weeks to investigate. But the tests I wrote for chameleon/london library should be fine.

**Comment by zaroth** [comment]
More tests are always welcome. Looks good :+1:

**Comment by mtgred** [comment]
:+1:

**Pull request merged**
