### PR TITLE
Fix breaker auto pump, and also re-implement Media Blitz

### PR DESCRIPTION
**Pull request by justinliew**
I missed a couple of changes in card-icebreakers

### CODE REVIEW

**Comment by zaroth** [comment]
It should be noted that this PR is in regards to Media Blitz implementation, from title it isn't immediately clear :)

**Comment by Saintis** [comment]
Is this still relevant?

**Comment by JoelCFC25** [comment]
I don't remember or understand all of what was going on here, but it would be nice to make Media Blitz work.

**Comment by erbridge** [comment]
I think the Media Blitz aspects of this PR are independent of the breaker changes, though it references functions that don't appear to exist in the codebase (`copy-events`, `copy-abilities`, `copy-leave-play-effects`, `fire-leave-play-effects`).

**Comment by JoelCFC25** [comment]
> it references functions that don't appear to exist in the codebase

Turns out that `copy-leave-play-effects` and `fire-leave-play-effects` can still be exhumed from #910!

**Comment by Saintis** [comment]
With #2197 merged I would say this can be closed.

**Pull request closed without merging**
