### PR TITLE
Displaying card previews in chat

### PR DESCRIPTION
**Pull request by jwarwick**
Fixes issue #2531 

Moved the chat state into the main app-state. Using text parsing and preview display code from the gameboard.

### CODE REVIEW

**Comment by danhut** [comment]
This will have a merge conflict with this
https://github.com/mtgred/netrunner/pull/2747

I think I need to change that one though as I merely renamed the chat atom. ???

**Comment by jwarwick** [comment]
Yes, there are a few things in the pull request queue that are going to have conflicts. I'm not sure what the project policy is on how to resolve those in general.

For #2747, since I've already moved everything into the main `app-state`, we should be able to just add the wrapper around the input div.

I can roll that change into my branch easily if you want.

**Comment by Saintis** [comment]
Generally what happens is some things get merged. Things with conflicts don't and then whoever has PRs with conflicts rebases and solves them 😉.

**Comment by jwarwick** [comment]
Okay, I can work with that 😃

**Comment by mtgred** [comment]
👍

**Pull request merged**
