### PR TITLE
Some minor things

### PR DESCRIPTION
**Pull request by Saintis**
Cleans a bit of code in damage stuff.
Implements Queen's Gambit - prompts when access prevented.
Fixes Agendas facedown on Film Critic.

screen shot 2016-09-28 at 19 28 59
screen shot 2016-09-28 at 20 06 16

Dev note: added a docstring to the multifunction formerly known as `access`, this does not indent nicely in IntelliJ + Cursive so I manually specified the indentation level as suggested [here](https://github.com/cursive-ide/cursive/issues/848)

### CODE REVIEW

**Comment by mtgred** [comment]
👍

**Comment by mtgred** [comment]
There are some merge conflicts. Can you have a look?

**Comment by Saintis** [comment]
Ready to merge again.

**Comment by mtgred** [comment]
👍

**Pull request merged**
