### PR TITLE
Improve some of the styling

### PR DESCRIPTION
**Pull request by erbridge**
- Make the game count orange to distinguish it from links in the navbar (works as grey, too).
- Wrap an `<il>` in a `<ul>` as it should be, and simplify the navbar styles (no visual changes).
- Tidy up indentation and spacing in the stylus files.

### CODE REVIEW

**Comment by nealterrell** [comment]
Can you post before & after screenshots?

**Comment by erbridge** [comment]
Sure, but the only change is "0 Games" goes from white to orange.

**Comment by zaroth** [comment]
when changing UI, quick visual appraisal is everything ;-)

**Comment by erbridge** [comment]
Sure. Not objecting :).

**Comment by erbridge** [comment]
Before:
screenshot from 2016-09-30 18-17-20

After:
screenshot from 2016-09-30 18-15-23

**Comment by zaroth** [comment]
I like the styling cleanup, but to be honest I'm not too convinced by the orange games count indicator... I think it's more confusing this way (by looking like either a hovered real link or a fake link (which also does something on hover).

**Comment by erbridge** [comment]
Yeah. We don't have a huge amount of variety in colours, though. Could go with grey?

**Comment by erbridge** [comment]
screenshot from 2016-10-12 18-17-24

**Comment by Saintis** [comment]
I like how sad it looks when there is only 1 game.

**Pull request merged**
