### PR TITLE
Add a basic user stats page

### LINKED ISSUE #892: statistics page in profile [Epic]
Wins and losses by deck visible to user
wins and losses by side visible by viewer

### PR DESCRIPTION
**Pull request by danhut**
* Ready to go *
screen shot 2017-10-02 at 6 57 54 pm

Fixes #892
Deck stats were added to the deckbuilder screen already

### CODE REVIEW

**Comment by JoelCFC25** [comment]
In keeping with past tense of "Started" and "Completed", I'd maybe opt for "Won" and "Lost". And do we really want people to be able to clear their stats? No strong feeling on it, just curious. I think if it ever came to pass, a won-lost-incomplete indicator on a public profile would be good info when considering if you really want to play someone. Serial game-leavers having that percentage publicized might save a lot of collective headaches.

**Comment by danhut** [comment]
Rationale for self clearing is to avoid people quitting games they might lose.   

Given Neal adding a rejoin function my feelings might change on the subject. As incomplete games will be more likely the player acting up

Will revisit once I expose the data elsewhere?

**Comment by danhut** [comment]
Or clearing is limited to win/lose as I dont want people to be put off or stress on the stats. 

Future could be tracking for the competitive room as distinct?

**Comment by mtgred** [comment]
Cool!

For consistency in the UI, can you put the buttons inside the blue pane?

**Comment by danhut** [comment]
@mtgred  Moved the buttons

**Comment by mtgred** [comment]
👍

**Pull request merged**
