### PR TITLE
Patron fix

### LINKED ISSUE #1575: Patron should be optional
Patron is currently set up to be a mandatory like Security Testing, but the card text says "may" so it should be an optional ability instead.

### PR DESCRIPTION
**Pull request by kevkcc**
Fixes #1575

### CODE REVIEW

**Comment by nealterrell** [comment]
I'd honestly rather add a "No server"  button to the Patron list. I know @queueseven suggested this course of action but I think it's over-engineering. We go from one mouse click (choose the server or No server) to 3 (click Patron; click server; click Take Clicks to start turn since we forced Step 1.2) if a server is desired (most common case) or 1 (Take Clicks) if no server is desired.

**Comment by queueseven** [comment]
Yeah, good idea, Neal. Less clicks are better.

**Comment by kevkcc** [comment]
Sure that's cool. Made the change.

**Comment by mtgred** [comment]
👍

**Pull request merged**
