### PR TITLE
Guard against card name being displayed during grip-to-grip movement

### LINKED ISSUE #86: Runner accidentally reveal grip cards
When Runner (idk if Corp does as well) accidentally moves card in his/her grip, status board on the right shows the name of the moved card, revealing it to the Corp.

### PR DESCRIPTION
**Pull request by chua-mbt**
Fixes #86

### CODE REVIEW

**Comment by queueseven** [comment]
Cool. Maybe you could also prevent the message when the corp moves a card in HQ? While it wont reveal the card name it's still confusing

**Comment by chua-mbt** [comment]
You mean suppress the system message entirely for both corp and runner for hand-to-hand movement? Sure.

**Comment by queueseven** [comment]
Yes. While you're on the run: it would be cool to display the previous zone also. So instead of `The runner moves a card to grip`, it would be cool to display something like `The runner moves a card from play to their grip` or `...from heap to their grip` and for the corp something like `The corp trashes a card installed in Server 2` etc. 

That's a bigger change, maybe you want to do it next :-)

**Comment by chua-mbt** [comment]
Done and done. Tweak the messages as needed.

**Comment by mtgred** [comment]
:+1:

**Pull request merged**
