### PR TITLE
Test case for Eater accessing card after trash

### LINKED ISSUE #4536: Eater - Can access after breaking subs, and getting trashed mid run.
Eater can access cards after using its paid ability to break subroutines, and then subsequently getting trashed mid run.

mnrix uses Eater to access not more than 0 cards for the remainder of this run.
limnrix pays 1  from Net Mercur and 1  from their credit pool to use Eater to break all 2 subroutines on NEXT Gold.
xdfubar has no further action.
limnrix continues the run.
xdfubar: thinking
xdfubar pays 1 .
limnrix pays 0 .
xdfubar uses Marcus Batty to resolve the subroutine (" Trash a program") from NEXT Gold.
xdfubar uses NEXT Gold to trash Eater.
xdfubar has no further action.
limnrix accesses Corporate Sales Team from Server 1.
limnrix steals Corporate Sales Team and gains 2 agenda points.
limnrix uses Mystic Maemi to add 1  to itself.
xdfubar
xdfubar
wait
limnrix accesses Surat City Grid from Server 1.
xdfubar
xdfubar
u cant access
limnrix
limnrix
oh weird

### PR DESCRIPTION
**Pull request by Kubik161**
Closes #4536 

Only test case, Eater works correctly.

### CODE REVIEW

**Comment by NoahTheDuke** [comment]
Can you check that there’s no prompt on successful run?

**Comment by Kubik161** [comment]
I thought this checks prompt on successful run:

        (run-successful state)
       ...
        (is (empty? (:prompt (get-runner))) "No prompt for accessing cards")))))

**Comment by NoahTheDuke** [comment]
In the previous test yes, but I mean in this new eat you added! Just a simple check at the end

**Comment by Kubik161** [comment]
it's also in this new test, but github doesn't mark it as changed line. But it's there...

**Comment by NoahTheDuke** [comment]
Oh shit haha I’m so sorry. Yes it is.

**Pull request merged**
