### PR TITLE
Some quick fixes (Liquidation, RNG Key, Psychographics)

### PR DESCRIPTION
**Pull request by kevkcc**
Psychographics rewritten so that you can't pay 5 credits to place 3 advancement tokens because the runner has 3 tags.

### CODE REVIEW

**Comment by NoahTheDuke** [comment]
Some agendas are installed face-up, so you shouldn’t be checking against that.

**Comment by kevkcc** [comment]
I thought faceup agendas weren't technically rezzed, that's why I put that in

**Comment by NoahTheDuke** [comment]
Hmmm lemme check on that

**Comment by NoahTheDuke** [comment]
> Faceup agendas are neither rezzed nor unrezzed.

3.2.3.a of Comp Rules v1.1. You’re right, the non-agenda req stays in!

**Pull request merged**
