### PR TITLE
Edward

### PR DESCRIPTION
**Pull request by DominicKexel**

### CODE REVIEW

**Comment by nealterrell** [comment]
Just as a minor code formatting concern, could you change `(if (not (some #{:discard} zone))` in `trash` to `when` instead of `if`, and then indent the body two spaces more?

**Comment by DominicKexel** [comment]
@nealterrell Done. But I fucked up merge :-(

**Comment by DominicKexel** [comment]
I tried to rebase my commits into one, but failed miserable. Will try again tomorrow.

**Comment by mtgred** [comment]
What does this pull request do actually?

**Comment by JoelCFC25** [comment]
This is a follow-on from discussion in #379. By the way, there's a typo in line 45 of Edward Kim ("alreay").

**Comment by DominicKexel** [comment]
Never mind with this PR, I'll close it and create a new one when I was able to clean up the commits.

**Pull request closed without merging**
