### PR TITLE
Installing from archives message consistency

### PR DESCRIPTION
**Pull request by zaroth**
Improved archives install message consistency of following cards: 

Interns
Team Sponsorship
Crick
Architect
Director Haas' Pet Project
Archived Memories

also fixed Crick being able to install from HQ

### CODE REVIEW

**Comment by nealterrell** [comment]
Nice job!

**Comment by GordonsBeard** [comment]
Once again we have commits in the .gitignore that add IDEA projects. We need to be more clear on whether or not this will be included in the project.

**Comment by zaroth** [comment]
@GordonsBeard I don't see why not, that's the function of .gitignore after all. It wouldn't bother me much if there were specified filters for every Clojure IDE in the world, as long as they were specific enough.

**Comment by nealterrell** [comment]
I believe @GordonsBeard is mentioning this because @mtgred asked him to remove a similar commit from another PR. I believe minh's preference is for the files to be ignored in `./git/info/exclude` rather than `.gitignore`.

**Comment by mtgred** [comment]
Editor / OS related config files should go to .gitignore file located in the user home directory. That is ~/.gitignore (Mac OS, Linux) or %USERPROFILE%\.gitignore (Windows)

**Comment by zaroth** [comment]
Rebased the branch and threw away commit with .gitignore changes.

**Comment by zaroth** [comment]
Also updated https://github.com/mtgred/netrunner/wiki/Getting-Started-with-Development

**Pull request merged**
