### PR TITLE
Update all our our instants for the ncigs changes

### LINKED ISSUE #7436: [WIP] Update all operations/event for NCIGS changes
You're allowed to play operations and events that have no tangible effect on the game state now (unless they have explicit instructions that you cannot play them). So this means there's (probably) quite a few to update.

I'm slowly going to go through all of these and get them out of the way.

### LINKED ISSUE #7439: Make a pass through all the operations and events, and give them `do nothing` lines if they can't do anything
Second step of the NCIGS changes for instants. See #7436, #7438

### PR DESCRIPTION
**Pull request by NBKelly**
Basically making sure you can play these cards when they have no legal targets. I think this concept is pretty silly, but it is what is.

See here: https://nullsignal.games/blog/ashes-remaster-rules-update/

>As a step towards removing the NCIGS rule, an ability that plays an event or operation no longer needs to look inside the effects of that event or operation for the player to be able to trigger it.

Closes #7436
Also Closes #7439 now, too

I've changed every single operation and event with an ncigs req (the actual play requirements of the card are the same). For anyone confused as to why the list is *so short*, it's because we weren't actually enforcing conditions on every single card anyway. The changes are only the ones where we enforced ncigs already.

What this means (a couple of examples):
* Eye for an Eye still requires that you're not tagged
* But it can be played if HQ is unrunnable, to do nothing (ie excalibur, can't pay for earth station)
* Fast Break can now be played to gain 0, draw up to 0 cards, and install up to 0 cards in a remote server

**I also added a bunch of messages that say `(xx) uses (yy) to do nothing` in cases where a card does nothing. This is distinct from declining to use an ability, so I did not use that phrasing.**

***In addition to the changes below, I went through (almost) every operation and event in the game and added in a `:change-in-game-state` key where appropriate if there are 1) no legal targets and 2) not even any pretend targets to bluff.***

Operations that were changed from having a req:
* 24/7 news cycle (you can play this to resolve no ability)
* Ad Blitz (you can play this with no targets)
* Ark Lockdown (you can play this when it can't possible do anything)
* Audacity (you can play this with no legal targets)
* Best Defense (you can play this when the runner has nothing installed)
* Big Deal (you can play this with no legal targets)
* Bioroid Effeciency Research (you can play this with no legal targets)
* Bring them Home (you can play this when the runner has no cards in hand)
* Building Blocks (you can play this with no legal targets)
* Economic Warfare (you can play this to do nothing, when the runner is under 4 credits)
* Exchange of Information (you can play this with no target)
* Fast Break (Draw up to 0, Gain 0, install up to 0 cards in a remote server)
* Financial Collapse (you can make the runner lose 0 credits)
* Liquidation (you can play this with no legal targets)
* MCA Informant (you can play this with no legal targets)
* Media Blitz (you can play this with no legal targets)
* ~~Mutate (you can play this with no legal targets)~~ nevermind, this one's a cost
* MAD (you can play this with no legal targets)
* Power Shutdown (You can play this if the runner has no hardware and you have no cards in the stack)
* Psychokinesis (you can play this with no deck)
* Red Planet Couriers (you can play this with no legal target)
* Retribution (you can play this when there are no legal targets)
* Sacrifice (you can play this with no agenda points, and with no  bad pub to remove)
* Trick of Light (you can play this with no legal targets)
* Your Digital Life (you can play this to gain 0 credits)

Events that were changed from having a req:
* Account Siphon (can do nothing)
* Bravado (You can play this with no legal targets to do nothing)
* Brute-Force-Hack (you can play this with no legal targets to spend any arbitrary amount of credits)
* Burner (you can play this when HQ isn't runnable to do nothing)
* Career Fair (you can play this when there aren't any legal targets)
* CBI Raid (you can play this when HQ isn't runnable to do nothing)
* Chastushka (you can play this when HQ isn't runnable to do nothing)
* Code Siphon (you can play this when R&D isn't runnable to do nothing)
* Data Breach (you can play this when R&D isn't runnable to do nothing)
* Deep Data Mining  (you can play this when R&D isn't runnable to do nothing)
* Deep Dive (you can play this when R&d is empty, in order to do nothing)
* Deja Vu (You can play this with an empty discard pile, in order to do nothing)
* Demolition Run (can only run runnable servers, and also have a "do nothing" choice if none exist)
* Diversion of Funds (you can play this when HQ isn't runnable to do nothing)
* Divide and Conquer (you can play this when Archives isn't runnable to do nothing)
* Embezzle (you can play this when HQ isn't runnable to do nothing)
* En Passant (you still need a successful run, but you can play this with no legal targets)
* Escher (you can play this when HQ isn't runnable to do nothing)
* Eye for an Eye (still requires no tag, but HQ not runnable can make it do nothing)
* Fear the Masses (you can play this when HQ isn't runnable to do nothing)
* Feint (you can play this when HQ isn't runnable to do nothing)
* Finality (you can play this when R&D isn't runnable to do nothing)
* Glut Cipher (you can play this when Archives isn't runnable to do nothing)
* Hot Pursuit (you can play this when HQ isn't runnable to do nothing)
* Immolation Script (you can play this when Archives isn't runnable to do nothing)
* Indexing (you can play this when R&D isn't runnable to do nothing)
* Information Sifting (you can play this when HQ isn't runnable to do nothing)
* Jailbreak (now no longer gives you the option for unrunnable targets)
* Joy ride (you can play this when R&D isn't runnable to do nothing)
* Khusyuk (you can play this when R&D isn't runnable to do nothing)
* Labor Rights (you can play this if you have no deck or discard)
* Legwork (you can play this when HQ isn't runnable to do nothing)
* Marathon (you can play this when there are no runnable remotes to do nothing)
* Mass Install (you can play this if you have no targets)
* Mobius (you can play this when R&D isn't runnable to do nothing)
* Networking (you can play this when you have no tags)
* On the Lam (you can play this with no valid target)
* Paper Tripping (you can play this with no tags)
* Political Graffiti (you can play this when Archives isn't runnable to do nothing)
* Privileged Access (you can play this when Archives isn't runnable to do nothing)
* Reboot (you can play this when Archives isn't runnable to do nothing)
* Retrieval Run (you can play this when Archives isn't runnable to do nothing)
* Rip Deal (you can play this when HQ isn't runnable to do nothing)
* Satellite Uplink (you can expose 0 cards)
* Showing Off (you can play this when R&D isn't runnable to do nothing)
* The Maker's Eye (you can play this when R&D isn't runnable to do nothing)
* The Price (you can trash 0 cards)
* Tinkering (you can play this with no valid targets)
* Trick Shot (you can play this when R&D isn't runnable to do nothing)
* Uninstall (you can play this with no valid targets)
* Vamp (you can play this when HQ isn't runnable to do nothing)
* Wanton Destruction (you can play this when HQ isn't runnable to do nothing)

### CODE REVIEW

**Comment by NoahTheDuke** [comment]
I read through a good chunk of the changes and I think you've done the process correctly, but I wonder if this is the right way to change the code. We've struggled with the readbility of "condition is nested, so don't use a `:req`" for years. I know you've already done the work to touch 450 lines of card impls 😬.

How would you feel about something that's like... `:condition` or something that would let the ability be marked as "executed" but in `game.core.engine/do-effect`, there'd be a last-minute check and if it's false, then instead it prints "does nothing".

**Comment by NBKelly** [comment]
Yeah, I do wonder if we're at the point where we can split things into `:req` (hard conditions/prerequisites, like *'play only if the runner is tagged'*) and `:does-something` (which defaults to true, and can be used like our old req functions to short-circuit abilities).

I'm definitely going to need some system like that for when nsg decides that you can use any paid abilities at any time for no reason :skull_and_crossbones: 

I'll give it a go and see if I can make it work.

**Comment by NBKelly** [comment]
ok so that worked, but I also had to add it in our prompt function so we can add (for example) `:does-something (req (seq (:deck corp)))` to accelerated diagnostics to short circuit it when the deck is empty.

This should work for our paid abilities too, so that solves the future problem nicely. I'll update a bunch of the cdefs over the next day or so.

**Comment by NoahTheDuke** [comment]
I am not a fan of :does-something. It's the wrong level of abstraction. Maybe :resolve-req or :apply-req or :cigs lol.

(Maybe now is the time to change :req to be something like `:condition` as that's the rules terminology.)

**Comment by NBKelly** [comment]
I think I'm going to use `:change-in-game-state`, because `:cigs` is too ugly.

Renaming our `:req` functions is a neat idea, but I think it's probably an issue for after nsg finishes their ncigs overhaul (presumably after dawn).

The task should also be significantly smaller by then.

**Comment by NBKelly** [comment]
OK, this should be good to go now I think.

**Comment by NoahTheDuke** [comment]
Oops, conflicts. Once you update, I'll merge.

**Pull request merged**
