### PR TITLE
Bad Publicity triggers and The Outfit

### PR DESCRIPTION
**Pull request by NoahTheDuke**
Changes out bad publicity is gained to mirror taking tags: in fact, this is a copy-paste of the tagging code, with the necessary changes, and all gain bad publicity references modified to follow suit.

This allows for The Outfit to work as needed: when gaining any amount of bad publicity, the effect triggers `:corp-gain-bad-publicity`, and the corp gains 3 credits.

### CODE REVIEW

**Comment by NoahTheDuke** [comment]
Note that this will require a change in Too Big To Fail (#3152), so as to use the new bad publicity gaining function.

**Comment by JoelCFC25** [comment]
Pretty cool. Shouldn't Broadcast Square have its ability hooked to a `:pre-bad-publicity` listener? And it doesn't have the capability to prevent just 1, it would prevent all inbound BP if there is ever a card that gives more than 1 at a time. For Profiteering, if you opted to take 2 or 3, then Broadcast Square kicked in and you prevented it all, you'd gain no Profiteering credits. Weird one there.

**Comment by NoahTheDuke** [comment]
Yeah, good call. I'll see if I can auto-wire that.

**Comment by NoahTheDuke** [comment]
There it is, all done. Broadcast Square, Profiteering, and The Outfit all work correctly. All necessary tests have been updated and work properly.

**Pull request merged**
