### PR TITLE
fix #561: dont show card text when img-url present

### LINKED ISSUE #561: Jinteki biotech showing the hidden identity
http://puu.sh/jHusa/c9915be62d.png <-upper right corner, just under where it shows their identity-card. One line of text.

### PR DESCRIPTION
**Pull request by DeepSpawn**
fixes #561 

screen shot 2016-11-11 at 11 58 28 pm

screen shot 2016-11-12 at 3 55 50 pm

Previously we were rendering the card text and then putting the img over the top of this.
When the card text was long this would result in card text being visible at the bottom.
We now only show the card text if we are unable to create the img url for the card.

### CODE REVIEW

**Comment by DeepSpawn** [comment]
Hey I have updated the PR based upon your feedback. 

I modified the card-view component to contain a state to determine if the it should show the text view or not, which defaults to false. The onError event handle updates the state of the component to toggle this, which will trigger a re-render of the component showing the text view.

(I tried to work out how to extract the text view code to a separate function but am not experienced enough with clojure to get it working so I have just left it as it is)

**Comment by DeepSpawn** [comment]
screen shot 2016-11-15 at 10 09 39 pm
When testing I noticed that the text view work correctly for identities, but not for other cards. I am not sure if this is expected behavior or not. I was able to reproduce it on master when the img url is hardcoded to something that will fail (attached screenshot is from master).

**Comment by DeepSpawn** [comment]
Hey @nealterrell how do I keep this PR moving? I changed my approach after you first looked at it and I think the current approach is a reasonable way of solving the problem.

**Comment by nealterrell** [comment]
Sorry about that, got caught up in dev server merges and then the holidays. Let me review and then authorize.

**Comment by nealterrell** [comment]
Could you clarify the screenshot you posted in your comment? I'm not sure what the issue is.

**Comment by DeepSpawn** [comment]
So that last screen shot is showing that we do not currently get the text for the card body when viewing non identity cards, we can see its name and type etc but not what the card actually does.

**Comment by nealterrell** [comment]
OK, I don't know why that is, but it's a very minor issue.

**Comment by mtgred** [comment]
👍

**Pull request merged**
