### PR TITLE
Update to deckbuilder for latest MWL rules

### PR DESCRIPTION
**Pull request by danhut**
Ready but likely needs to wait on NRDB API update - as I assume players would rather have MWL 1.1 rules rather than something in between.

Tried this out for the following:
1/ 3 universal inf cards (mongoDB manual update)
2/ The "17-influence Omar" deck - now illegal
3/ Infinite inf ID

It assumes NRDB update the MWL API to just show the universal inf as a value where they always have one as the val today.   It will need a change if they do something else.

https://netrunnerdb.com/api/2.0/public/mwl

{"data":[{"id":1,"date_creation":"-001-11-30T00:00:00+00:00","date_update":"2016-08-01T00:00:03+00:00","code":"NAPD_MWL_1.0","name":"NAPD MWL 1.0","active":false,"date_start":"2016-02-01","cards":{"01012":1,"01014":1,"01024":1,"01081":1,"01092":1,"02110":1,"03038":1,"04029":1,"04119":1,"06061":1,"06099":1}},{"id":5,"date_creation":"2016-07-12T19:18:47+00:00","date_update":"2016-08-01T00:00:03+00:00","code":"NAPD_MWL_1.1","name":"NAPD MWL 1.1","active":true,"date_start":"2016-08-01","cards":{"01012":1,"01014":1,"01016":1,"01024":1,"01082":1,"01092":1,"02110":1,"03038":1,"04029":1,"04119":1,"06033":1,"06061":1,"06099":1,"08061":1,"10018":1}}],"total":2,"success":true,"version_number":"2.0","last_updated":"2016-08-01T00:00:03+00:00"}

### CODE REVIEW

**Comment by JoelCFC25** [comment]
As long as you are doing something that needs all the ClojureScript recompiled, maybe take care of the bracket/parens issue on the Help page that is screwing up the console commands section? It's line 48 and then some other places further down where things need to be closed up properly.

**Comment by danhut** [comment]
done - looks like it was busted by #2437

**Comment by dodgepong** [comment]
There's some discussion about how NRDB is going to handle the two different MWL styles here: https://github.com/zaroth/netrunner-cards-json/pull/208

**Comment by danhut** [comment]
@dodgepong Thanks.  Tested against this and looks good to me.

**Pull request merged**
