### PR TITLE
use regex patter with word boundaries...

### PR DESCRIPTION
**Pull request by DominicKexel**
..to match only the exact name.

Relates to case mtgred/netrunner#429

### CODE REVIEW

**Comment by mtgred** [comment]
:+1:

**Comment by hydrozen** [comment]
@mtgred @queueseven  I’m trying to figure out a solution, but this seems to have broken links in the message pane for cards such as Snare!, Shock! and Shi.Kyù, I’m guessing because `!` and `.` are related to word boundaries.

**Comment by queueseven** [comment]
@hydrozen yeah, there's already a fix in another currently open pull request

**Comment by hydrozen** [comment]
@queueseven which PR?

**Comment by JoelCFC25** [comment]
#490

**Comment by hydrozen** [comment]
@queueseven ah its been merged already. Not sure I understand the new regexp ;) Cool that it is fixed though nice work.

**Comment by queueseven** [comment]
@hydrozen it's a kind of hack because the javascript regex engine has neither balancing groups nor look-behind expressions.

**Comment by hydrozen** [comment]
@queueseven mind explaining what it’s matching exactly, in words? I’m just curious.

It looks like this: `(^|[^\[\S])Snare!(?![~\w])` right? I’m not sure I understand both sides of the regexp.

**Comment by queueseven** [comment]
The first part `(^|[^\[\S])` matches the start of the string or not [ or not non-white space; maybe I could just have used `(^|\s)`, but my brain as probably already melted at that time I wrote that.

The `(?![~\w])` at the end only matches if the string does not end with a word character or `~`.

The function scans the text for card names, like *Gang Sign*, and then replaces it with `[Gang Sign~01234]`, where `01234` is basically the name of the image file. So the `(?![~\w])` part ensures that after creating `[Pop-up Window~98787`], the `Window`-part does not get replaced with `[Window~56473]`, since there's also the card `Window`.

One idea was to simply change the server side code to send the `[card title~number]` strings itself, but I didn't want to change every line in `core.clj` and `cards.clj` where the title of a card is used in a message. Also, I think it's quite cool that you can type *"Is Gang Sign broken?"* in the chat and the card is linked automatically.

**Pull request merged**
