### PR TITLE
Implement Rutherford Grid

### PR DESCRIPTION
**Pull request by queueseven**

### CODE REVIEW

**Comment by mtgred** [comment]
The `req` macro provides a shortcut for "run on this server".

You can replace `(req (> (java.util.Collections/indexOfSubList (vec (:zone card)) (vec (get-in @state [:run :server]))) 0))` with `(req (this-server))`.

**Comment by queueseven** [comment]
@mtgred Ah, good to know! Thanks!

**Comment by queueseven** [comment]
@mtgred I changed the card to use `(req (this-server))`

**Comment by mtgred** [comment]
:+1:

**Pull request merged**
