### PR TITLE
Adding pt translation

### PR DESCRIPTION
**Pull request by Vacilotto**
Adding on the translations file the Portuguese section.

### CODE REVIEW

**Comment by csbisa** [comment]
This is missing an addition to the options side. You'll have to add something here: https://github.com/mtgred/netrunner/blob/master/src/cljs/nr/account.cljs#L289

**Comment by NoahTheDuke** [comment]
If you can update the account file, I'd love to merge this.

**Comment by Vacilotto** [comment]
Sorry about the delay. Will work on it this week.

**Comment by Vacilotto** [comment]
@csbisa added the line in account.cljs, thank you <3
@NoahTheDuke I think it's ready to merge now :)

**Pull request merged**
