### PR TITLE
Display text or images in card browser

### PR DESCRIPTION
**Pull request by elmarco**
It is convenient to be able to copy & paste or search in the text of cards.

The second patch is just cleanup (unless it's useful for debugging?).

(I have no prior experience with om/clojure, so this might not be the best way to do it, I welcome help or ideas)

### CODE REVIEW

**Comment by elmarco** [comment]
Screenshot:
text

**Comment by nealterrell** [comment]
Did you test this change on a live game? `card-view` is used in `gameboard.cljs` for displaying the card zoom view, and is also used in `deckbuilder.cljs`. By adding a third parameter to the method I am concerned you may have broken those.

(Props for the use of `partial`, though.)

**Comment by elmarco** [comment]
You are right, I broke `deckbuilder`, however, it seems `gameboard` uses its own `card-view`.
Fixing it, by using a partial. I am not particularly proud of using it there, I was looking for a way to give the `:appearance` state to the component. I don't think it's the "om" way what I did.

**Comment by nealterrell** [comment]
Look for `cb/card-view` at the end of gameboard.

**Comment by elmarco** [comment]
Ok, will fix it.

Btw, not sure where to ask this, but since you are quite familiar with the project, let me ask. clojurescript+react seems quite awesome, and I am glad to learn it. However, since I am considering writing a game engine (for conquest), would you say that clojure was/is a good choice? Reading the code, I am not quite convinced of using functional programming is really a win. Any opinions?

**Comment by nealterrell** [comment]
Clojure(Script) wouldn't have been my first choice if I was founding a project like this; I probably would have thought to make a more traditional backend in ASP.NET (my only real web backend experience) with a JS user interface. I do like that the game engine and UI can be written in the same language with Clojure(Script), and have come to greatly enjoy working with Clojure, but there are other languages that can also do this (JavaScript via Node, Scala(.js)). I think functional programming is a style that every skilled programmer can and should incorporate into most software projects, but I don't always agree with pure-functional approaches to complicated software like games.

**Comment by zaroth** [comment]
It may be a good idea if you want to attract to project bored programmers thirsty for some functional programming distraction, though ;-)

**Comment by elmarco** [comment]
Hi Neal, unfortunately, I am quite busy with other projects these days. Feel free to pick up where I left off.

**Comment by Saintis** [comment]
@jwarwick is this PR still relevant after #2727 has been merged?

**Comment by jwarwick** [comment]
@Saintis probably safe to close it. I think #2727 added the same functionality in a slightly different way.

**Pull request closed without merging**
