### PR TITLE
:watch-path so shadow-cljs picks up and injects changed css correctly

### PR DESCRIPTION
**Pull request by queueseven**
This should fix css hot reloading.

### CODE REVIEW

**Comment by queueseven** [comment]
I don't want to push changes myself, even if they are so small. I think it would be better if at least one other person confirms that this works now, even if this is such a minor thing.... 🤔

**Review by NoahTheDuke — COMMENTED** [review]
I thought these overlapped. You need both?

**Comment by queueseven** [comment]
@NoahTheDuke Well, we could remove `:watch-dir`, then shadow-cljs will watch for changes in the entire root folder (as far as I understand it), but since we know that our css is in the `resources/public/css`, it doesn't hurt to keep it. The important part is `:watch-path "/css"`

**Comment by NoahTheDuke** [comment]
And it knows to search subdirectories for that path?

**Pull request merged**
