### PR TITLE
When installing a card in a remote, don't remove that remote

### PR DESCRIPTION
**Pull request by DominicKexel**
fixes mtgred/netrunner#393 and mtgred/netrunner#156

When you installed an asset/agenda in a remote n that already had an
asset/agenda, that already installed card got trashed.

Then that server was removed from the game, and the remove server n+1
became server n, since the remotes are implicitly numbered.

Then the new asset/agenda was installed in server n, which was the wrong
server.

### CODE REVIEW

**Comment by mtgred** [comment]
:+1:

**Comment by mtgred** [comment]
The server has been updated with the latest commit. There seems to be an issue with remote server removal now. Server 0 contains a rezzed Eve Campaign with no ICE, Server 1 contains an agenda with no ICE. I run server 0 and trash Eve Campaign. Server 0 is not removed. Agenda in Server 1 is scored. Server 1 is removed but Server 0 is still there.

**Comment by DominicKexel** [comment]
Mmmh.... Didn't noticed while testing. I'll take a look.

**Comment by DominicKexel** [comment]
Sorry for the inconvenience. Here's the fix for the fix: #406.

Trashing should only prevent the destruction of the server if the `:keep-server-alive` flag is set.

**Pull request merged**
