### PR TITLE
Block users from the lobby chat screen

### PR DESCRIPTION
**Pull request by jwarwick**
**Need some help with styling**, but the functionality is in place. Click a button by the username in a chat message, they get added to your block list. You get a toast message with confirmation and reminder to refresh your browser.

It should be possible to update the Om state and get it to redraw automatically, but I can't seem to make that happen.

You don't get a button by your username (`test2` in the screenshot) or when not logged in.

screen shot 2018-03-11 at 9 07 59 pm

### CODE REVIEW

**Comment by nealterrell** [comment]
I'd rather this be tied to a menu that appears when clicking the user's name. Eventually that menu could be expanded with Add Friends, PM, etc.

**Comment by jwarwick** [comment]
Makes sense. Do you imagine a context menu? That might be confusing, since we can't trigger it with a right click. Doing a full page overlay (like the login prompt) is probably easier.

**Comment by nealterrell** [comment]
I had pictured something similar to the card ability pop-in menu.

**Comment by jwarwick** [comment]
Okay, that's more the context menu I was envisioning. I'll take a stab at that and see how it looks.

**Comment by jwarwick** [comment]
Reworked so that when you click on a username in chat you get a menu. The cursor changes when you mouse over another user (but not your name). Clicking the name when the menu is open closes the menu. Selecting `Cancel` closes the menu.

screen shot 2018-03-17 at 5 43 44 pm

**Pull request merged**
