### PR TITLE
Update 'In the Groove' for Hayley Kaplan interaction

### PR DESCRIPTION
**Pull request by merrickbrown**
This is in response to issue #5628

### CODE REVIEW

**Comment by NoahTheDuke** [comment]
Thank you so much for tackling this issue! I don't want to get into the habit of making exceptions for single cards, so I think a better option here is to just remove the Hayley part and leave the `first-event?` check. That way, it will still pause for Hayley, and we can look at other interactions as they come in.

**Comment by merrickbrown** [comment]
Yep - makes sense, I noticed there weren't any such exceptions (eg no tests for :title in conditions) so I'm not surprised this is a policy. I went ahead and updated the :interaction value as requested

**Comment by merrickbrown** [comment]
One question, is it preferable to target `dev` or `master` for changes?

**Comment by NoahTheDuke** [comment]
Master. A long long time ago, we tried to use dev as a staging/working branch, but it was too difficult to keep everything in sync so we abandoned it. I should probably remove that branch.

**Pull request merged**
