### PR TITLE
Chameleon bug fix

### PR DESCRIPTION
**Pull request by kevkcc**
Hello,

I have submitted what I believe is a fix for issue #977, as well as 325/409. I play a lot of Hayley so I decided to do something about it. I am new and this is my first time submitting anything so please let me know if I messed up anywhere.

### CODE REVIEW

**Comment by JoelCFC25** [comment]
Works on my end--great job! Any chance you're up for writing a unit test? :)

**Comment by kevkcc** [comment]
Yea absolutely, is there a guide of some sort I can refer to?

**Comment by mtgred** [comment]
:+1:

**Comment by JoelCFC25** [comment]
@kevkcc  The starting documentation for the unit testing framework is in its initial PR at #736. You can probably cobble together the rest of what you'd need just by mimicking other existing card tests. If you need any pointers come join us on the Slack!

**Pull request merged**
