### PR TITLE
modifies engine to accept ability-title as an input parameter for events

### PR DESCRIPTION
**Pull request by NBKelly**
This is probably not the best way to do it, but tbh that entire system seems a bit confusing to me.

This should allow multiple events on the same card with the same timing to be named and arbitrarily fired in any order. It also means you can name some of the triggers, though I'm not sure we need it right now.

I'll figure out a cleaner way to write this a bit later, just had to put it up while I remembered.

### CODE REVIEW

**Comment by NoahTheDuke** [comment]
Hard to review without a demonstration

**Comment by NBKelly** [comment]
No worries.

Here's a simple example where the (1996) card 'Butcher Boy' registers a handler against the runner ID (it needs to persist indefinitely, even if the card vanishes). Since it's registered under the ID, it's competing with MaxX to trigger first.

Prior to this change, you wouldn't be able to distinguish the triggers or pick which trigger to resolve first.

demo

demo1

demo2

I probably still need to rewrite this to be a bit less hacky.

**Comment by NoahTheDuke** [comment]
This is good but after thinking about it a bit, best to hold off until we have a need in jnet proper.

**Comment by NoahTheDuke** [comment]
I think we need this now? Or did you end up adding it in another PR that we've since merged? Either way, status?

**Comment by NBKelly** [comment]
Oh, I don't think we need it yet. Sooner or later we might, so it's fine to let this one sit.

**Comment by NoahTheDuke** [comment]
This was done on the other pr, right?

**Comment by NBKelly** [comment]
Yeah, I'm going to close this one

**Pull request closed without merging**
