### PR TITLE
Save games to off-site database instance

### PR DESCRIPTION
**Pull request by domtancredi**
Will need environment variables set to the new database

### CODE REVIEW

**Comment by nealterrell** [comment]
@mtgred this PR is to turn game statistics back on by offloading the data to an Azure instance that @justinliew and @domtancredi collaborated on. They can provide more details about the server in Slack, including the connection strings.

**Comment by mtgred** [comment]
The stats code need some rework. Saving the full game states not only take a lot of disk space, it also make the aggregation queries run forever.

I'm currently learning Datomic and will add code to save summary game data in Datomic soon. The really cool thing about Datomic is that it has time travel built in. It's like using Git instead of only keeping the latest version of the code. The time travel will allow to analyse game stats overt time.

**Comment by domtancredi** [comment]
That's very interesting and I'm reading up on Datomic. Very elegant separation of concerns model for data lifecycle. I like the idea of "facts" and allowing to persist that state of things via them. 

Should this branch stay alive? Is it of value? It'd be really great to store game data right now, at least, so we can present stats over Feb // March, etc. until Datomic is implemented.

What's the timetable for bringing in Datomic?

**Comment by zaroth** [comment]
Connected to #1123.

**Comment by nealterrell** [comment]
Closing this now, since we no longer have the coffee server.

**Pull request closed without merging**
