### PR TITLE
Muertos - fix #2294

### LINKED ISSUE #2294: Muertos Gang Member triggers when trashed while hosted
If Muertos Gang Member is trashed while hosted (say, on Street Peddler) but not installed, the corp player is still given a prompt to rez for free.

### PR DESCRIPTION
**Pull request by danhut**
Fix for this problem as suggested by @JoelCFC25 

fix #2294

### CODE REVIEW

**Comment by nealterrell** [comment]
Is this the right fix? The text is not "When Muertos is trashed", it's "when uninstalled", which `:leave-play` seems correct for. I think the real problem is firing `:leave-play` for cards that are not in play (facedown, or hosted but not installed).

**Comment by JoelCFC25** [comment]
#2358 is relevant here. Anything resource or hardware hosted on The Supplier that has a `:leave-play` effect is seeing it fired when The Supplier gets trashed. I _think_ this is the only existing case of Runner cards being hosted, faceup, and inactive currently? 

I didn't get around to thorough testing, but a quick change to `trigger-leave-effect` [here](https://github.com/mtgred/netrunner/blob/master/src/clj/game/core/installing.clj#L25) to add a check for `installed` seemed promising. At least solved the Brain Chip case.

**Comment by danhut** [comment]
I don't think I even understand what the hell "uninstalled" even means.  How does something get uninstalled without being trashed?  I am trying to think of a card - any ideas?  Maybe i need to read the rules again!

**Comment by nealterrell** [comment]
Archangel, Uninstall (the card), Bird breakers uninstall themselves, etc.
It's rare but they use that wording for a reason.

**Comment by danhut** [comment]
Thanks - then clearly this is not the right fix.

**Comment by danhut** [comment]
This might sound crazy but I feel like when Muertos leaves play off Peddler it actually enters play temporarily.  I took out the facedown check from here in BOLD - and when Peddler is trashed it actually fires the install effect from Muertos. 

Will have more of a poke around tonight.

```
(defn- trigger-leave-effect
  "Triggers leave effects for specified card if relevant"
  [state side {:keys [disabled installed rezzed facedown zone host] :as card}]
  (when-let [leave-effect (:leave-play (card-def card))]
    (when (and (not disabled)
               (or (and (= (:side card) "Runner") installed (not facedown))
                   rezzed
                   **(and host (not facedown))**  
                   (= (first zone) :current)
                   (= (first zone) :scored)))
(leave-effect state side (make-eid state) card nil)))
```

**Comment by danhut** [comment]
I spent a while staring at this to no effect... then tried the Cursive debugger for the first time.  To me it looks like when Peddler is trashed - that Muertos is no longer facedown.  Hence the leave effect fires

screen shot 2017-02-08 at 11 18 02 pm

Will look more at a better hour unless someone tells me what this means ;0

**Comment by JoelCFC25** [comment]
I'm still pretty sure changing line 25 that I referenced earlier is enough. 

Current: `(and host (not facedown))`

Proposed: `(and host installed (not facedown))`

Have now tested both the Brain Chip on Supplier (hosted, faceup, inactive) and Muertos Gang Member on Peddler (hosted, facedown, inactive) and none of the unwanted effects appear.

**Comment by danhut** [comment]
This does not work for me.  Test failures:

```
lein test :only test.cards.resources/muertos-street-peddler

FAIL in (all-tests muertos-street-peddler) (resources.clj:748)
Corp not prompted to rez Jackson
expected: (empty? (:prompt (get-corp)))
  actual: (not (empty? ({:cancel-effect nil, :end-effect nil, :msg "Choose a card to derez", :choices ["Done"], :card {:faction "Criminal", :limited 3, :runner-abilities (), :zone [:rig :resource], :cid 3746, :new true, :type "Resource", :abilities ({:label "Draw 1 card"}), :title "Muertos Gang Member", :uniqueness false, :host nil, :code "08068", :side "Runner", :cost 0, :hosted nil, :subroutines (), :installed true, :implementation :full, :subtype "Connection", :previous-zone (:onhost)}, :priority nil, :show-discard nil, :effect #object[game.core$show_select$fn__6139 0x1df73457 "game.core$show_select$fn__6139@1df73457"], :eid {:eid 44}, :prompt-type :select})))


lein test :only test.cards.operations/wetwork-refit

FAIL in (all-tests wetwork-refit) (operations.clj:1368)
Eli 1.0 has 1 different subroutine
expected: (= 1 (count (:subroutines (refresh eli))))
  actual: (not (= 1 2))

lein test :only test.cards.operations/wetwork-refit

FAIL in (all-tests wetwork-refit) (operations.clj:1370)
Eli 1.0 has an end the run subroutine as his first subroutine
expected: (= "End the run" (:label (first (:subroutines (refresh eli)))))
  actual: (not (= "End the run" "Do 1 brain damage"))
```


Here is my local-only test case for Muertos & Peddler (and Brain chip - which looks fixed)
```
(deftest muertos-street-peddler
  ;; Muertos uninstall effect not fired when removed off peddler/hosting Issue #2294
  (do-game
    (new-game (default-corp [(qty "Jackson Howard" 1)])
              (default-runner [(qty "Street Peddler" 2)(qty "Muertos Gang Member" 1) (qty "Brain Chip" 1)]))
    (starting-hand state :runner ["Street Peddler" "Street Peddler"])
    (core/move state :runner (find-card "Street Peddler" (:hand (get-runner))) :deck {:front true})
    (play-from-hand state :corp "Jackson Howard" "New remote")
    (take-credits state :corp)
    (play-from-hand state :runner "Street Peddler")
    (core/gain state :runner :agenda-point 1)
    (let [jh (get-content state :remote1 0)
          sp (get-in @state [:runner :rig :resource 0])]
      (core/rez state :corp jh)
      (is (empty? (:prompt (get-corp))) "Corp not prompted to de-rez Jackson")
      (card-ability state :runner sp 0)
      (prompt-card :runner (-> (get-runner) :prompt first :choices first)) ; choose another Peddler
      (is (empty? (:prompt (get-corp))) "Corp not prompted to rez Jackson")
      (is (= 4 (:memory (get-runner))) "Runner has 4 MU"))))
```

**Comment by JoelCFC25** [comment]
Yeah, I dunno. I've had so many battles with Tri-maf/MGM in the past that I just cannot bring myself to look at it anymore.

**Comment by danhut** [comment]
From the debug - I see Muertos is moved to the discards before the leave-effect.  The move to discard clears the facedown flag and voila the ability gets fired.  Seems viable to attempt to fire the leave effect before the card gets moved.

I don't have your scars yet!

**Comment by JoelCFC25** [comment]
So the sequence of functions when a Peddler-hosted MGM hits the bin is: 

Case: Someone else on Peddler was installed
`trash` -> `resolve-trash` -> `resolve-trash-end` -> `move` (in the topmost `let`)

Case: Peddler itself was trashed, all hosted cards lost
`trash` -> `resolve-trash` -> `resolve-trash-end` -> `move` -> `trash-hosted` -> which takes you to the first step of the previous case

Ultimately, the logic has to get adjusted in `move`, I think.

**Comment by danhut** [comment]
I agree Joel.  I am thinking we could change trash-hosted as it is today:
```
             trash-hosted (fn [h]
                             (trash state side
                               (dissoc (update-in h [:zone] #(map to-keyword %)) :facedown)
                               {:unpreventable true})
                               ())
```
We could remove the dissoc :facedown from here for the runner side - and have the dissoc happen at the end of the move.   Any card in discard for runner must be face-up so we could do this later.

I am trying to think if there is any problem with this even for the corp.  I don't think so.

**Comment by JoelCFC25** [comment]
If memory serves, `:facedown` is literally never used for Corp cards.

**Comment by danhut** [comment]
The below appears to work.  Any thoughts?  I will open a new PR to make the code clear - and close those one if it looks good.

In cards.clj - take out the dissoc facedown from trash-hosted

OLD
```
             trash-hosted (fn [h]
                             (trash state side
                               (dissoc (update-in h [:zone] #(map to-keyword %)) :facedown)
                                    {:unpreventable true})
                               ())
```
NEW:
```
             trash-hosted (fn [h]
                             (trash state side
                                    (update-in h [:zone] #(map to-keyword %))
                                    {:unpreventable true})
                               ())
```

When the card is moved to discard we call the function Deactivate which then calls dissoc-card - which itself already does a dissoc for :facedown

I don't know the history as to why this was done twice

```
(defn- dissoc-card
  "Dissoc relevant keys in card"
  [card keep-counter]
  (let [c (dissoc card :current-strength :abilities :subroutines :runner-abilities :rezzed :special :new
                  :added-virus-counter :subtype-target)
        c (if keep-counter c (dissoc c :counter :rec-counter :advance-counter :extra-advance-counter))]
    (if (and (= (:side c) "Runner") (not= (last (:zone c)) :facedown))
      (dissoc c :installed :facedown :counter :rec-counter :pump :server-target) c)))
```


Updated combined test for brain chip and muertos
```
(deftest muertos-street-peddler
  ;; Muertos uninstall effect not fired when removed off peddler/hosting Issue #2294
  (do-game
    (new-game (default-corp [(qty "Jackson Howard" 1)])
              (default-runner [(qty "Street Peddler" 2)(qty "Muertos Gang Member" 1) (qty "Brain Chip" 1)]))
    (core/move state :runner (find-card "Muertos Gang Member" (:hand (get-runner))) :deck {:front true})
    (core/move state :runner (find-card "Brain Chip" (:hand (get-runner))) :deck {:front true})
    (core/move state :runner (find-card "Street Peddler" (:hand (get-runner))) :deck {:front true})
    (play-from-hand state :corp "Jackson Howard" "New remote")
    (take-credits state :corp)
    (play-from-hand state :runner "Street Peddler")
    (core/gain state :runner :agenda-point 1)
    (let [jh (get-content state :remote1 0)
          sp (get-in @state [:runner :rig :resource 0])]
      (core/rez state :corp jh)
      (card-ability state :runner sp 0)
      (prompt-card :runner (find-card "Street Peddler" (:hosted sp))) ; choose to another Peddler
      (is (empty? (:prompt (get-corp))) "Corp not prompted to rez Jackson")
      (is (= 4 (:memory (get-runner))) "Runner has 4 MU"))))
```

**Comment by danhut** [comment]
Tentative commit here:
[link](https://github.com/mtgred/netrunner/compare/master...danhut:muertos_take2)

**Pull request closed without merging**
