### PR TITLE
Minor fixes

### LINKED ISSUE #1912: Clone Suffrage Movement log
When an operation is returned from Archives to HQ via Clone Suffrage Movement, the log displays simply "a card" regardless of the faceup/facedown status. With things like Jackson Howard shuffling cards back in, "X cards" refers to facedown cards, while faceup cards are directly named in the log (as it's open information). Is it possible to get Clone Suffrage Movement to work the same?

### PR DESCRIPTION
**Pull request by Hoclor**
A set of minor fixes/implementations to different cards (Hive, Sherlock 2.0, TL;DR, Clone Suffrage Moevement)

Fixes #1912.

### CODE REVIEW

**Comment by Hoclor** [comment]
The Clone Suffrage Movement change doesn't seem to have shipped with this, I will look into this tomorrow.

**Comment by JoelCFC25** [comment]
You can add "fix" or "fixes" followed by an issue reference (the Clone Suffrage one, in this case) in your comments to have the issue get closed automatically when the PR is merged.

**Comment by Hoclor** [comment]
Thanks for the tip! Edited my top comment to include this

**Comment by mtgred** [comment]
👍

**Pull request merged**
