### PR TITLE
Add "waiting on..." prompts to fix some card interactions

### PR DESCRIPTION
**Pull request by nealterrell**
This introduces the ability to show a "Waiting for ..." prompt to a user at the front of their prompt queue, preventing them from interacting with other prompts until some other card or function clears the waiting prompt. This is intended to fix several tricky card interactions like #576, #423, #907, and #289; plus some general game flow issues like #956, #329, and unreported issues with psi games and traces.

Example: Runner accesses a Snare! with a Dedicated Response Team rezzed. Corp sees the "Pay 4cr to use Snare?" prompt while the Runner simultaneously sees "Pay 0cr to trash Snare?". If the runner finishes his prompt first, then the run will be finished and "successful run ends" events will trigger. Dedicated Response Team will see that event but won't damage the runner because they are not tagged (yet). Corp then chooses to use Snare! to give the tag and damage, but it's too late for DRT to fire. This happens because the runner's ability to trash (and thus end the run) is allowed before the Corp has decided to trigger the Snare. Similar issues occur with Manhunt (the trace dialogs are still active when the runner accesses) and Ghost Branch... basically, any ability that needs to be resolved with a prompt by one player, but also needs to block further actions by the other player.

`show-wait-prompt` is a new function to add a "Waiting for..." prompt to a player's queue. The prompt has no buttons, as shown here:

image

The only way to dismiss the prompt is with `clear-wait-prompt` as part of a card or engine function. 

I have used this feature in the following ways:

* Mulligans: Runner sees "waiting for Corp to keep hand or mulligan" until that happens, then vice versa. Game then can start. (These are only shown if two players are in the game.) I moved the Keep/Mulligan stuff out of the UI (where it was hard-coded) and reimplemented it as prompts in the game engine.
* Traces: when a trace triggers, the Runner sees "waiting for Corp to initiate trace", preventing other actions like accessing. After initiating, the Corp sees "waiting for Runner to boost Link strength".
* Psi games: whomever bids first sees "[opponent] is choosing psi credits" until that is done. Prevents Runner from starting to access a second Future Perfect in Archives while a first FP's psi game is resolving.
* Snare! and Ghost Branch: because these are optional, they will block the Runner from acting until the Corp decides to trigger, which fixes the DRT issue outlined above.
* Chronos Protocol: runner sees "waiting for Corp to use Chronos Protocol" until the CP dialogs are complete. 

### Prompt priorities

I expanded (and documented) the `:priority` prompt system so that it's no longer binary. Priorities are now numerical, and prompts are inserted into the prompt queue in decreasing priority order. If two prompts have the same priority, then whichever was inserted first will remain first in the sort. `:priority true` is interpreted as `:priority 1`, and no priority is `:priority 0`. `show-wait-prompt` will by default insert a priority 1 wait prompt, but takes an optional parameter to change that priority as needed (Manhunt required trace prompts to be priority 2).

FINALLY, I added a `/close-prompt` chat command to remove the currently active prompt, just in case

### CODE REVIEW

**Comment by mtgred** [comment]
There is a merge conflict. Can you have a look at it?

**Comment by nealterrell** [comment]
Done!

**Comment by nealterrell** [comment]
Extended functionality to Edge of World, with test.

**Comment by mtgred** [comment]
:+1:

**Pull request merged**
