### PR TITLE
Show number of cards in hand and credits...

### PR DESCRIPTION
**Pull request by queueseven**
...at the start and end of turn. Also show a horizontal line.

This makes it easier (logically and visually) to follow up the game's progress

bild 30

### CODE REVIEW

**Comment by JHonaker** [comment]
I really like this. I'm probably going to pick your brain about front end stuff at some point. I've never done any front end development.

**Comment by nealterrell** [comment]
"startet"?

**Comment by queueseven** [comment]
@nealterrell It's fixed in the code already :-)

**Comment by mtgred** [comment]
:+1:

**Pull request merged**
