### PR TITLE
Feature account random background

### PR DESCRIPTION
**Pull request by domtancredi**
Added an Account View, for managing the user's account + profile.
Added navigation to the view
Added updating the background image (visible in the gameboard when playing or spectating: had to update the opacity 1 instead of 0.7)

Could use some code review and possible refactoring

### CODE REVIEW

**Comment by domtancredi** [comment]
Also, to respond to Issue #70

**Comment by nealterrell** [comment]
@domtancredi can you resolve the conflicts so I can try to move this forward with Minh?

**Comment by zaroth** [comment]
"My Account" is visible in two places, in top navbar and in the user dropdown menu. What's the reason for this?

**Comment by domtancredi** [comment]
Easy accessibility. We can remove it from either location. I suggest dropping from the dropdown menu until the top nav becomes too big

**Comment by JoelCFC25** [comment]
What would it take to get this updated to merge with the current code? Any chance of screenshots?

**Comment by domtancredi** [comment]
Ok, this branch is updated to latest on master.

Screenshot: http://puu.sh/q4HCO/a9ebba9e4c.png

It could use some testing, and some TLC on layout, however this is the baseline for a "my account" section of the site.

**Comment by nealterrell** [comment]
@mtgred I'd like to see this merged to get a foundation going for further development on profile and friend-related features. @domtancredi, can you add a "Change" link next to the Avatar on the profile page that links to http://www.jinteki.net/help#avatar?

**Comment by JoelCFC25** [comment]
Can it also be made to modify the email address associated with the account? There's at least 1 open issue about that request.

**Comment by domtancredi** [comment]
@nealterrell will add the "Change" link to link out
@JoelCFC25 yes, though we should step through the business logic for this, as it is entirely custom

High-level steps:

1. update your profile with a new email address, 
2. send a "new confirmation" to that address, 
3. confirm that address from a link, 
4. finalize the "changed address" in the database with the new address (overwrite the old address)

Up until step 4, you can "drop out" of the process and still retain your existing email address

**Pull request merged**
