### PR TITLE
Toastr fix.

### PR DESCRIPTION
**Pull request by Saintis**
Placed libs in wrong place. This fixes that. Run `bower install` after merge to get libs properly.

### CODE REVIEW

**Comment by Saintis** [comment]
Also fixes the test failure for Snare!

**Comment by Saintis** [comment]
Fixes persisten toasting for econ assets as well.

**Comment by Saintis** [comment]
@mtgred This should fix the test failures on `master`, and optional ability error.

**Comment by mtgred** [comment]
:+1:

**Pull request merged**
