### PR TITLE
Use npm scripts rather than global modules

### PR DESCRIPTION
**Pull request by erbridge**
This removes the requirement to globally install Coffeescript and Bower (and make sure they're at the correct versions). It also simplifies the installation process.

### CODE REVIEW

**Comment by zaroth** [comment]
Does npm still install coffeescript this way even if there was one installed globally from the distro's repository?

**Comment by erbridge** [comment]
Yup. NPM will always install all local dependencies regardless of what's installed globally. Their executables get put in `node_modules/.bin`, but NPM scripts add it to the path, so local dependencies are preferred over global ones. Obviously, manually running `coffee` from a terminal will still use the global version (unless they do some clever stuff to actually run the local version instead, which some CLIs do).

**Comment by erbridge** [comment]
Oh, and it's probably worth mentioning that some of the scripts are special, like `postinstall` which always gets executed immediately after `npm install`.

See: https://docs.npmjs.com/misc/scripts.

**Comment by mtgred** [comment]
👍

**Pull request merged**
