### PR TITLE
Keeping hosted cards when moving a card within the same root zone

### LINKED ISSUE #549: Builder trashes Parasite when click effect used.
As the title says, Builder currently auto-trashes Parasite when the click effect is used to move it. Builder never leaves play, so Parasite should stay hosted on the card. I asked Lukas just to verify and this was his response from Twitter:

Nick Stoppiello ‏@iamtrilkin  16 minutes ago
@RukasuFox Quick rules question: if Builder is hosting Parasite and Builder's click effect is used to move it, does Parasite get trashed?

Lukas Litzsinger ‏@RukasuFox  15 seconds ago
@iamtrilkin No it doesn't trash the Parasite.

### PR DESCRIPTION
**Pull request by chua-mbt**
Fixes #549

### CODE REVIEW

**Comment by JoelCFC25** [comment]
@chua-mbt  I still think this is a great addition, but it is probably showing conflicts due to the `move` definition having changed since you submitted this. Are you able to sync to the current code and patch this back in?

**Comment by chua-mbt** [comment]
I'll rebase master into this branch when I have time. Do you have tests that can be run now?

**Comment by JoelCFC25** [comment]
Some, but for the most part they get written as needed. :)

**Comment by zaroth** [comment]
If this one got a test and was rebased onto current master, it'd be great :)

**Comment by JoelCFC25** [comment]
I just checked back into this one briefly--making these additions to `move` (now found in core-cards.clj) yields an almost-correct result. Specific to the initial bug report that spawned this, moving a Builder that's hosting a Parasite correctly takes the Parasite with it...but the Parasite stops accumulating tokens at the start of subsequent Runner turns.

**Comment by queueseven** [comment]
Hey @chua-mbt, any update on this?

**Comment by chua-mbt** [comment]
I'll try to look into this sometime within the next two weeks. I'm a bit busy with work atm.

**Comment by chua-mbt** [comment]
Better late than never. 

* Added a regression test since the project now has tests.
* Updated my old changes to ```move```
* Fixed event registration for the hosted cards that moved with the host (thanks @nealterrell )

**Comment by nealterrell** [comment]
This is ready to merge, @mtgred.

**Comment by mtgred** [comment]
👍

**Pull request merged**
