### PR TITLE
Ganked raindrops interaction

### LINKED ISSUE #7773: Ganked + Raindrops interaction
I don't have a replay on hand, but what happened was:
Runner runs a server with Raindrops. The outermost ice fires but doesn't ETR due to Bankhar.
Runner accesses a Ganked! and encounters the same ice again, which now does ETR.
Raindrops gains counters and draws cards only from the first encounter sub activations.

### PR DESCRIPTION
**Pull request by NBKelly**
Following the rabbit hole to it's logical conclusion and trying to figure out why forced encounters specifically don't fire subroutine events before the run ends, but regular encounters do, was too hard.

Raindrops is the only card that interacts with subroutines like this, so I moved the event back a tiny bit to make sure it always gets caught.

Closes #7773

### CODE REVIEW

**Comment by NoahTheDuke** [comment]
As you probably suspected, this fix is wrong, but I'm also not sure how it's wrong. I think given nothing else interacts here we can merge and move on, but i'll have to think about this a little bit more.

**Comment by NBKelly** [comment]
yeah, I just spent hours trying to unravel the gordian knot of code in `runs.clj` and couldn't figure out a specific point I could change to fix it :joy:

**Comment by NoahTheDuke** [comment]
i suspect it comes from how we have two eids going at once when a rund ends: the runs original eid and the player action eid when they click the button or whatever to perform an action to end the run. i still don't know how to fix  that

**Comment by NBKelly** [comment]
Yeah - this is exclusive to forced encounters during the access phase, so it's particularly troublesome to figure out :weary:

**Pull request merged**
