### PR TITLE
Implement The All-Seeing I

### PR DESCRIPTION
**Pull request by JHonaker**

### CODE REVIEW

**Comment by mtgred** [comment]
:+1:

**Comment by queueseven** [comment]
@JHonaker Maybe you want to remove the `(prn (not (zero? (:bad-publicity corp))))` part? :-)

**Comment by JHonaker** [comment]
I stared at this for about 10 minutes before I realized the prn was the problem. 

I'll remove it.

**Comment by queueseven** [comment]
Sorry, didn't want to waste your time :-)

**Comment by mtgred** [comment]
You can also replace `req` with `effect` and remove the `state` and `side` in the `resolve-ability` call.

**Comment by JHonaker** [comment]
I fixed it in the latest pull request with Tori Hanzo.

**Pull request merged**
