### PR TITLE
DJ Fenris in da Haus!

### PR DESCRIPTION
**Pull request by Saintis**
"Totally not too hard to implement" - said no-one ever about DJ Fenris. Got it working now though. Probably needs a lot more tests (like Rebirth). Does one card on #3184.

As the other PRs, tests are failing due to Akiko (I hope).

Some pics:
screen shot 2018-03-12 at 22 15 59
(Selection for Apex)

screen shot 2018-03-13 at 01 02 49
(Quetzal hosted on DJ Fenris)

I can confirm that Chaos Theor (test checks that) and Quetzal (I've tried it) works.

EDIT: Looks like I got Neal's PR in there as well. I'm guessing merges will sort that out... Good news is that test isn't failing though...

### CODE REVIEW

**Comment by danhut** [comment]
I wonder what happens with Ayla here?  I suspect you could click her to get the hosted ID into her hand?  eeek...

**Comment by Saintis** [comment]
I changed `move` to move all Identity cards to RFG exclusively (so you can’t drag the hosted id to your hand). I should update that now when I made the hosted id be of type “Fake-Identity”. Will do tomorrow

**Comment by Saintis** [comment]
Test failing due to NRDB 500 error. Haven't run on local machine so do not merge until test passes.

**Comment by Saintis** [comment]
Not quite done yet, will revisit soon.

DO NOT MERGE :)

**Comment by Saintis** [comment]
Now ready for review and merge. Tests passive modifiers (CT) and passive abilities (Geist).

**Pull request merged**
