### PR TITLE
Implement Surfer; fix Bullfrog, Sneakdoor Beta & Susanoo-No-Mikoto

### PR DESCRIPTION
**Pull request by queueseven**

### CODE REVIEW

**Comment by queueseven** [comment]
Barrier subtype can't be enforced because we have no way to alter the subtypes of cards at the moment (think of Tinkering and Paintbrush).

**Comment by mtgred** [comment]
There is a merge conflict with Escher. I can't have a look at it right now. Can you merge master and resolve the conflict?

**Comment by JoelCFC25** [comment]
It might be that in one of my PRs that got merged I changed the messaging in Escher to use "ICE" instead of "ice" to be consistent with all other cards...

**Comment by queueseven** [comment]
merge done.

**Comment by JoelCFC25** [comment]
Now that you merged, can you update Copycat to take out the initial `(let [ice-index ...` since it's a core function added in this PR? Thanks!

**Comment by queueseven** [comment]
@JoelCFC25 Done.

I also sneaked in a fix for Datasucker

**Comment by mtgred** [comment]
:+1:

**Pull request merged**
