### PR TITLE
Apocalypse

### PR DESCRIPTION
**Pull request by kevkcc**
I noticed that Apocalypse had a few problems when I was playing with respect to hosted cards and memory (#1192). I have submitted a fix and a test for these issues. I also noticed during my testing that Leprechaun could also host 3 cards on it so I made a quick fix to that too.

### CODE REVIEW

**Comment by kevkcc** [comment]
Has anybody looked at this?

**Comment by zaroth** [comment]
Well, Apocalypse has always been a bit of a mess, so you'll see no opposition from me to fix the state of things. Also the changes are tested, so overall big :+1: from me.

**Comment by nealterrell** [comment]
Looks good :+1:

**Comment by mtgred** [comment]
:+1:

**Pull request merged**
