### PR TITLE
Chronos

### PR DESCRIPTION
**Pull request by justinliew**
Chronos is manual. When the first Net damage is incurred, it will inform the corp they can use the ID to either pick a card and then it does N-1 net damage. There are 2 ID abilities: what was just described, or one where they can just do all the net damage without revealing, as it's a "may" ability.

### CODE REVIEW

**Comment by justinliew** [comment]
Joel gave me some pointers so I'm going to refactor the ability to be optional. Plus some slight messaging changes to make it more consistent.

**Comment by justinliew** [comment]
Aite, this seems to work better. Same functionality but no ID clicking. Asks you on first net damage and then functionality is the same.

**Comment by justinliew** [comment]
I've added :non-distinct so duplicates will show multiple times in order to be less confusing.

**Comment by mtgred** [comment]
:+1:

**Pull request merged**
