### PR TITLE
implement signal jam

### PR DESCRIPTION
**Pull request by danhut**
Test fail due to Ayla + Rebirth. Fixed in #2391 already

### CODE REVIEW

**Comment by JoelCFC25** [comment]
Wow, sweet. I actually thought of another (never seen) card that could do mid-run installs--Savoir-faire!

**Comment by danhut** [comment]
For cards I did not "augment" there is a toast and they are not allowed to install. I can check those but it is quite safe. Main thing was to stop wasted SMC and Peddlers.

**Comment by danhut** [comment]
Because they self trash before install is fired

**Comment by danhut** [comment]
Added some extra checks for Artist Colony, DaVinci, Savoir-Faire to stop them getting waste.  I don't think it is needed for any others.

**Pull request merged**
