### PR TITLE
Enforce MU limits when installing

### PR DESCRIPTION
**Pull request by NoahTheDuke**
see #6469

### CODE REVIEW

**Comment by queueseven** [comment]
I took the liberty to play aorund with these changes. There's an edge case that does not work correctly:

I have all my memory used up, have 2 or more link and want to install [ZU.13 Key Master](https://netrunnerdb.com/en/card/02007), a cloud breaker.

I can't install it as the 'Insufficient MU'-prompt will always be opened, but Key Master should have a memory cost of 0.

**Comment by NoahTheDuke** [comment]
Thanks so much for looking at this. I'll check that out!

**Comment by queueseven** [comment]
I'm also currently looking, but I don't really know how the :constant-effects stuff works.... 😂🤔

**Comment by queueseven** [comment]
I'm looking forward to seeing what your solution looks like, lol

**Comment by NBKelly** [comment]
One edge case that might be worth testing - if I'm replacing my console with another console (swapping out masterwork for another masterwork to cycle a card, for example) I shouldn't be forced to trash any programs under the current CR.

**Pull request merged**
