### PR TITLE
Displaying card text in card browser

### PR DESCRIPTION
**Pull request by jwarwick**
An attempt to implement what was proposed in Pull Request #1851 

Displaying the text information on the card below the filters panel when a card image is clicked.
Verified it still works correctly in the deck builder.

### CODE REVIEW

**Comment by danhut** [comment]
I loaded this pull locally and it looks great.  nice work!
Also could be a basis for this if you are feeling ambitious ;)

https://github.com/mtgred/netrunner/issues/2637

**Comment by jwarwick** [comment]
Ha! No front end skills and no language skills - could get ugly real quick :)
Do you guys have a dev channel to discuss these sorts of things?

**Comment by danhut** [comment]
There is a Slack channel - details here of who to contact at the bottom
https://github.com/mtgred/netrunner/wiki/Getting-Started-with-Development

**Comment by mtgred** [comment]
There are merge conflicts. Can you have look at it?

**Comment by jwarwick** [comment]
@mtgred merged changes

**Comment by mtgred** [comment]
👍

**Pull request merged**
