### PR TITLE
Fix for Autoscripter

### PR DESCRIPTION
**Pull request by DominicKexel**
Hosted cards no longer stay in thier original zone, but gets moved to a zone called `:onhost`.

When a card gets moved, the previous zone is now saved in `:previous-zone`

### CODE REVIEW

**Comment by nealterrell** [comment]
Nice job with Exile and Autoscripter. I don't know the hosting mechanism well enough to predict any complications from using `:zone :onhost`, so @mtgred will have to chime in on that. Have you tested this change with cards that are currently able to target hosted cards when applicable? (Foxfire and The Personal Touch would be two good prototypical cards to test.)

**Comment by DominicKexel** [comment]
Thanks.

The zone of a card does not matter in this case. Important is if a card is installed or not, regardless if it is hosted or not. 

Example: 

- when you play a Parasite on a piece of ICE, it's installed and hosted. 
- if you use PW's ability to host a card, that card is hosted but *not* installed.

The cards you mentioned correctly check the  `:installed` property of thier target, so there's no problem :-)

**Comment by DominicKexel** [comment]
So, the FAQ says that Foxfire can only target installed cards, so nevermind about what I said about it. Thanks for the info, Neal

**Comment by mtgred** [comment]
:+1:

**Pull request merged**
