### PR TITLE
Support for alternate art cards

### PR DESCRIPTION
**Pull request by jwarwick**
With lots of help from @nealterrell 
Alt art picker in account settings.
Alt art identity picker in deck builder
Alt art displayed in card browser

### CODE REVIEW

**Comment by nealterrell** [comment]
@mtgred This addresses several concerns from the first iteration of the alt art editor:

1. Clicking an art image will select that image, instead of only when clicking the radio button.
2. A bulk "set all to [official, alt, world champ 2015]" button.
3. The art section only shows up once all cards are loaded. (No more empty list while cards are being loaded.)
4. The first card in the list is automatically selected.
5. Styles moved from inline to .sty files.

**Comment by mtgred** [comment]
Great!

There are some conflicts with the latest merges. Can you have a look?

**Comment by jwarwick** [comment]
@mtgred merged `cardbrowser` and `package.json` conflicts

**Comment by mtgred** [comment]
👍

**Pull request merged**
