### PR TITLE
Toasts!

### PR DESCRIPTION
**Pull request by Saintis**
Adds toastr stuff.

Currently toasting:
- End-turn with too many cards
- `can-pay?` returning false (in most cases - not for Peddler and Supplier)
- Reconnect and disconnect (not tested)
- Having unrezzed econ assets (toasting on a per-card basis)
- Tennin Institute when relevant

Might help with #904 and #842.

### CODE REVIEW

**Comment by nealterrell** [comment]
Can you collect some screenshots?

**Comment by Saintis** [comment]
Screenshots:
pay-toast
info toast

**Comment by Saintis** [comment]
Tennin toast + econ rez toast: 
tennin toast

**Comment by zaroth** [comment]
Well, this is simply an awesome addition :)

**Comment by mtgred** [comment]
:+1:

**Pull request merged**
