### PR TITLE
Deckbuilder fixes and MWL restricted validation

### PR DESCRIPTION
**Pull request by zaroth**
A few screenshots of the functionality:

0f8b39b7_o
4f2bf010_o

### CODE REVIEW

**Comment by Saintis** [comment]
:+1: 

Like the big dots, is it possibly to get them more vertically aligned? I think they currently look a few pixels too low.

Also can we get a screenshot of the neutral faction influence colours?

**Comment by zaroth** [comment]
They look well aligned and smaller on my Windows computer - I think it's a browser font issue, not much we can do about it. Unless forcing a particular font with CSS... I'll take a look.

**Comment by zaroth** [comment]
Added fix for multiple lines containing same card (e.g. 2x 3 Sure Gambles)

**Comment by mtgred** [comment]
:+1:

**Pull request merged**
