### PR TITLE
implement mark command

### PR DESCRIPTION
**Pull request by francescopellegrini**
Additional work for #6436

### CODE REVIEW

**Comment by francescopellegrini** [comment]
See also #6439

**Review by NoahTheDuke — APPROVED** [review]
Add a test for this and the other command PR?

**Comment by francescopellegrini** [comment]
> Add a test for this and the other command PR?

Do commands have tests? 😅 

I tested them running the Docker compose and creating a new game. :)

**Comment by NoahTheDuke** [comment]
Yeah, there's a commands_test.clj file, should be pretty easy to just verify with a single call that it works.

**Pull request merged**
