### PR TITLE
Leela can only push Corp cards

### PR DESCRIPTION
**Pull request by justinliew**
Addresses https://github.com/mtgred/netrunner/issues/455. Check if the side is Corp as a requirement.

### CODE REVIEW

**Comment by justinliew** [comment]
Sorry for the messy branch. I'm new to github. Hopefully it results in just the single change showing up.

**Comment by nealterrell** [comment]
@justinliew: try rebasing your commits on your local repository to merge them into one commit message. (Look up `git rebase -i`.) Then "force" push your repository to your GitHub branch with `git push --force`. That should make your GitHub branch look exactly like your local repository, with the commits merged into one.

**Comment by justinliew** [comment]
@nealterrell - thanks, I'll give that a try. I've run into limitations with the UI client so I've started moving more to command line as it feels like things like these are easier and more flexible that way.

**Comment by justinliew** [comment]
I'll retry this properly, taking Neal's comments into consideration.

**Pull request closed without merging**
