### PR TITLE
Added faction icons to started games in game lobby

### PR DESCRIPTION
**Pull request by zaroth**
Replaced `(Corp)` and `(Runner)` with faction icons in game lobby display. The icons won't be displayed in three cases:

- the game hasn't started yet
- a neutral corp/runner is used (i.e. shadow/masque)
- `server.coffee` doesn't provide `:faction` (this will happen when either deck identity doesn't have the `:faction` key or old version of `server.coffee` is used)

5759a19e95878a41

`server.coffee` needs to be restarted after pulling these changes.

### CODE REVIEW

**Comment by Saintis** [comment]
Great stuff!

If you could make them specify ID on hover that would be mega awesome!

**Comment by zaroth** [comment]
They do! It's the `title` part :)

**Comment by Saintis** [comment]
Would that specify e.g. "NBN: Making News" or just "NBN", and similarly with e.g. "Noise", "Anarch"?

**Comment by zaroth** [comment]
Ah, you meant ID, not faction... I misunderstood. I could add that very easily, but my concern was with sent volume. Probably misplaced though, I'll add that soon :)

**Comment by zaroth** [comment]
Added identity tooltip as per @Saintis suggestion, thanks!

**Comment by jaerme** [comment]
This is awesome!

**Comment by mtgred** [comment]
:+1:

**Pull request merged**
