### PR TITLE
Enable card preview in log window and prompts

### LINKED ISSUE #4: Suggestion: Cards names in chat
First of all, congrats on a great job. Can't wait to see it finished. If it is something I can do, I will be glad to help. I'm a web developer, and can help on javascript, jquery, html and mongodb.

I want to make a suggestion. What if card names in chat offers a card view when hovering? Just like when you hover an actual card.

Best regards.
Víctor.

### LINKED ISSUE #216: Preview cards by hovering on title in chat (or on accesses)
Whenever you access something that does not require any interaction (like Hedge Fund), the only thing that's displayed is: "You accessed Hedge Fund".

If a user wishes to know what Hedge Fund is, they need to open up a separate tab and look up the card, which is technically against the rules. It would be nice to be able to hover over the text "Hedge Fund" (or any card text in chat) and have the card preview image appear where the card preview images normally appear.

### LINKED ISSUE #319: Exposing a card should show the enlarged card information
Although exposing a card shows the name of the card in the chat, players who aren't familiar with the card have no idea what it is.

It would be nice if the card was actually exposed in the UI for the player. One suggestion is to have a "ghost" version of the card (opacity ~50%) and when the runner mouses over the card, they can see a pop up. Maybe it lasts for the turn, for example.

### PR DESCRIPTION
**Pull request by DominicKexel**
Fixes #4
Fixes #216
Fixes #319

Also, it enables you to type some special words that gets translated to the netrunner icons, like `[Credit]` or `[c]`/`[$]` for the credit symbol, `[Trash]` or `[t]` for the trash symbol, etc.

### CODE REVIEW

**Comment by nealterrell** [comment]
This is really impressive. It even works with Prompt windows when accessing! Mind sharing how it works, specifically how you identify a card's title in strings in the chat log? Also, can we get some CSS to change the style of card titles to make it clear you can interact with them?

Well done!

**Comment by nealterrell** [comment]
Also, how about enabling this for prompt _buttons_? So I can hover the options when popping SMC to see the cards I am choosing between.

**Comment by DominicKexel** [comment]
Thanks.

When a new log message is created, I simply replace every possible card title in the message with a special  `[title~code]` string. The next step is to split the resulting string by the `[...]` parts and create a `<span>` element for each part (check if it's a Symbol, a card, or other text).

For prompts, the same code is used.

This will not work if there's ever a card with a title that is a substring of another card's title. If this is ever the case, the cards must be sorted descending by the length of the title. But I think it's fine for now :-)

Adding another CSS for card titles is easy. I had the idea myself, but I didnt want to change to much. Maybe simply making the text cursive would be enough?

**Comment by mtgred** [comment]
Awesome :+1:

**Pull request merged**
