### PR TITLE
WIP: Implement all ICE On Encounter abilities

### PR DESCRIPTION
**Pull request by NoahTheDuke**
This is a feature branch to track my status on implementing all manual On Encounter abilities across all ICE. I got Data Raven to work, so now I suspect I can do the same with the rest. We'll see?!?

- [ ] Authenticator
- [ ] Brainstorm??
- [ ] Bulwark
- [ ] Data Loop
- [x] Data Raven
- [ ] Data Ward
- [ ] Information Overload
- [ ] Jua
- [ ] Matrix Analyzer
- [ ] Oduduwa
- [ ] Pop-up Window
- [ ] Quicksand
- [ ] Snoop
- [ ] Thoth
- [ ] TL;DR
- [x] Tollbooth
- [ ] Troll
- [ ] Turnpike

### CODE REVIEW

**Comment by nealterrell** [comment]
How do you plan to deal with Inside Job etc?

**Comment by NoahTheDuke** [comment]
Honestly, hadn’t thought that far ahead. When I get to work on this later today, I’ll see what I can do about that interaction.

**Comment by JoelCFC25** [comment]
Inside Job, Spear Phishing, Rigged Results, Feint....but Hunting Grounds might be the worst of all.

**Comment by Saintis** [comment]
Femme as well.

**Comment by NoahTheDuke** [comment]
Yeah, this is a much bigger issue than I initially realized, haha. Gonna
have to see if I can develop a bypass mechanic (and a "can't be bypassed"
mechanic for Guard) before/concurrently with this project.

**Comment by NoahTheDuke** [comment]
I’ve decided that until there are some fundamental changes to jnet, it isn’t worth putting more time into this. Maybe in some far flung future!

**Pull request closed without merging**
