### PR TITLE
#1517 Fix Palana getting a credit for Adam's starting directives

### LINKED ISSUE #1517: Palana Gets a Credit at the Start of a Game Against Adam
I think when the game starts, Palana's ability treats the installation of the Directives as a draw somehow, and it gains a credit. Pretty minor and easily accounted-for bug, but I thought I'd mention it.

Thanks

### PR DESCRIPTION
**Pull request by IanWhalen**
Fixes #1517

### CODE REVIEW

**Comment by JoelCFC25** [comment]
Nice! There's a convenient way of auto-closing issues (when a PR is merged, that is) by using [these kind of references](https://help.github.com/articles/closing-issues-via-commit-messages/) either in a commit message or PR message.

**Comment by IanWhalen** [comment]
Oh yeah, sorry, I thought I was doing that with the "#1517 Fix..." part of the commit message.  Do I need to rewrite it as "Fix #1517..." for it to work?

**Comment by JoelCFC25** [comment]
Yeah, it's one of the magic words (fix, fixes, resolves, etc) _followed_ by the issue number. I edited it in for you, no worries!

**Comment by mtgred** [comment]
👍

**Pull request merged**
